### ISSUE TITLE
Op level 1 still have all commands

### ISSUE THREAD

**Issue by xion87** [weaondara/BungeePerms#103]
i tried to use 
op-permission-level=1 on server.proprietes
and seem the opped player still got all permissions.... i tried in a clean spigot and it work fine, so i think that is a issue with bungeeperms.
The rule of this config must follow as this:
1 - Ops can bypass spawn protection.
2 - Ops can use /clear, /difficulty, /effect, /gamemode, /gamerule, /give, and /tp, and can edit command blocks.
3 - Ops can use /ban, /deop, /kick, and /op.
4 - Ops can use /stop.

also i tried to negate the permission and seem to do nothing (maybe is related?)
-minecraft.command.op.take
-minecraft.command.op.give

in my config:
allowops: false
servername: hub
useregexperms: true
superpermscompat: true

**Comment by weaondara** [comment]
does it work now with this config?

**Comment by weaondara** [comment]
the latest dev build should fix it

**Comment by xion87** [comment]
i tried to use that, but with your new dev, all op dont have any permission with level 1 also with level 4

**Comment by weaondara** [comment]
allowops is still false? if so, that's intended
if true then ops should have permissions

**Comment by xion87** [comment]
tried to use allowops, i can't execute any command...

**Comment by xion87** [comment]
also i got the right permission for use admin chat, and i can't use it also if i am opped.

**Comment by weaondara** [comment]
did you also enable superpermscompat?

**Comment by xion87** [comment]
yep,  all permission was working fine before upgrade

**Comment by weaondara** [comment]
is superpermscompat enabled right now?

**Comment by xion87** [comment]
this is my config if you don't trust me http://hastebin.com/moqemotipu.sm

**Comment by weaondara** [comment]
@xion87 still not working?
i took a look into spigot source and i couldn't find a distinct between the op levels ... just op or not op
