### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by flamboo** [weaondara/BungeePerms#106]
Hi, I am using BungeeTabListPlus (http://www.spigotmc.org/resources/bungeetablistplus.313/) And I can not get any prefixes to work except the groups with "*" node. Can you please help me, Is there something I need to add ?

**Comment by phil568622** [comment]
? What's the Issue here?

**Comment by weaondara** [comment]
default.yml
```
tabList:
- '[SKIN=loiwiol]&2Rang: {prefix}'
```

config.yml
```
permissionSource: BUNGEEPERMS
```

i think that's it

**Comment by flamboo** [comment]
Yer i have that but still the prefixes don't show.

**Comment by weaondara** [comment]
i can't find any further config options in our btlp config
i also cannot find other options in the btlp wiki

**Comment by weaondara** [comment]
maybe you should ask the dev(s) of btlp ... this is not really a bungeeperms problem ...
