### ISSUE TITLE
UUID Mapping - Table Crash

### ISSUE THREAD

**Issue by Nosxxx** [weaondara/BungeePerms#107]
Hey,
since some time my uuid mapping table (mysql) crashes sometime (marked as corrupt).
I'm using MariaDB 10 on Debian Wheezy.

http://hastebin.com/qawutilanu.coffee

**Comment by weaondara** [comment]
mariadb is NOT officially supported eventhough it works
it seems that maria db has some serious bugs

possible solution: repair and optimize the table
maybe change db engine to innodb if you like
