### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by wacossusca34** [weaondara/BungeePerms#109]
There's a CI server up that builds with maven, with a repository on the same box (/var/lib/jenkins/.m2/). Why not install to a location on a web server directory so that developers can use the artifacts from the maven repo in their own projects? It's literally a simple change in your POM and a few changes to the Apache configuration to allow file browsing.

Just trying to get around the annoyance of installing the artifacts to a local repository, or the repo on a different server.

**Comment by weaondara** [comment]
that's my aim ... had no time to do it but this do it soon

**Comment by phil568622** [comment]
Weaondara, when you have limited time, what about working on this project together with someone? I didn't learn java, but I think tuxilliator or sb else would be able to help.

Just an idea ;)

**Comment by weaondara** [comment]
done

**Comment by weaondara** [comment]
http://repo.wea-ondara.net/repository/public/

**Comment by sgdc3** [comment]
why :( jenkin's solution is more stable and simple

**Comment by wacossusca34** [comment]
@sgdc3 Jenkins and maven are two very different things. One is a continuous integration server, the other is a build automation tool.

**Comment by sgdc3** [comment]
@wacossusca34 I know, I work with them very often. The thing i'm saying is that using the jenkin's built-in maven 
 server is more easy and reliable.

**Comment by sgdc3** [comment]
(I'm talking about this: https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Maven+Repository+Server)

**Comment by sgdc3** [comment]
An example: the authme jenkins. It ptrovides CI (ci.xephi.fr) but also a maven repo for every job (ci.xephi.fr/plugin/repository/) without any deploy configuration. Fast, more secure and it uses less hardware resources compared to a complete webserver maybe hosted on another server.

**Comment by weaondara** [comment]
the jenkins plugin create a weird maven repos structure like http://jenkins-server:port/plugin/repository/project/helloworld/Build/4/repository/org/example/helloworld/1.0-SNAPSHOT/helloworld-1.0-SNAPSHOT.pom
i took a look at the plugin as it would have been the simplest way to do it but it did not meet my requirements
btw the resources are not a problem ....

**Comment by sgdc3** [comment]
@weaondara No, that's not right. Look at my jenkins: http://ci.xephi.fr/plugin/repository/everything/
The "everything" path doesn't apply any "per project" filter. Everything is like a normal mvn repo.

**Comment by sgdc3** [comment]
The only difference is that SNAPSHOTs and RELEASEs are in the same repo, but this isn't a real issue.
