### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ZehrMC** [weaondara/BungeePerms#110]
Ok so the basic of this ENTIRE plugin isn't working. Server permissions, global permissions, literally nothing is working. I have Bungeecord 1.8+ and I have the BungeecordPerms 1.3 alpha..

**Comment by phil568622** [comment]
Have you configured the mysql database?

**Comment by ZehrMC** [comment]
What?

**Comment by phil568622** [comment]
Okay. For the communication between Bungee and Bukkit, you need a MySQL database, on your vServer for example. This plugin needs more than just drag & drop into the plugins folder.

Have you got a Virtual Server or Rootserver?

**Comment by ZehrMC** [comment]
I have the plugin on my BungeeCord plugins folder..

**Comment by ZehrMC** [comment]
How do I make it work?

**Comment by ZehrMC** [comment]
Yes I have the database

**Comment by phil568622** [comment]
Okay, please upload a server log to pastebin and post the link here

**Comment by ZehrMC** [comment]
Ok, but please know I am using the BungeePerms not the Bukkit/Spigot

**Comment by ZehrMC** [comment]
http://pastebin.com/G2atLwuZ

**Comment by phil568622** [comment]
There are two types of Permissions:

Bungeecord Permissions:
Commands like /server /send or sth. like that

Minecraft/Bukkit Permissions:
For example /stop /op /tp...

With BUNGEEperms you can control BOTH types. But you NEED a mysql database

http://en.wikipedia.org/wiki/MySQL 

If you only want the plugin to control BUNGEE permissions, you don't need one. But then you can't give players access to /to, for example

So please tell me what you want...

**Comment by ZehrMC** [comment]
I want the permissions to be global, meaning, if I rank you ADMIN from Hub you're ranked ADMIN on ALL the servers

**Comment by phil568622** [comment]
I see... 

Server log please.

There for you NEED a mysql database. Its like a file stored outside of the Minecraft server. When you now give rank admin to a player, the change is saved into the database, and the other instances read it from there.

But do you want the ranks to be based on Minecraft perms or bungee permissions?

**Comment by phil568622** [comment]
Another question, where are your servers running?
Linux Vserver or at a Minecraft server hoster?

**Comment by ZehrMC** [comment]
Minecraft server hoster

**Comment by ZehrMC** [comment]
So do I use BungeePermsBukkit and put the same config in all of them?

**Comment by phil568622** [comment]
Do you want the ranks to be based on Minecraft perms or bungee permissions?

**Comment by ZehrMC** [comment]
Plugin permissions like essentials, auction, faction etc

**Comment by phil568622** [comment]
Okay, you NEED to get a mysql database.

Maybe look for mysql offers at your hoster's shop

Again, please post a server log here...

**Comment by ZehrMC** [comment]
My server hosting company has MySQL databases I can make them.

**Comment by phil568622** [comment]
Yeah please do that

**Comment by ZehrMC** [comment]
Ok, I did,

**Comment by phil568622** [comment]
Now drop the plugin .jar to you Bukkit "plugins" folder and restart the server

**Comment by ZehrMC** [comment]
Do you have Skype?

**Comment by ZehrMC** [comment]
So I can screenshare and you can tell me

**Comment by phil568622** [comment]
No, I'm not using Skype. Have you installed BungeePerms on your Bukkit server?

**Comment by ZehrMC** [comment]
But why is it going to be in the Bukkit, shouldn't it be in Bungeecord's plugin folder?

**Comment by phil568622** [comment]
Plugin permissions, like essentials can't be controlled through a bungee side plugin. But Weaondara has made an adapter for BungeePerms, that can be installed at spigot / Bukkit servers and can control Bukkit plugins.

**Comment by phil568622** [comment]
So please put the credentials of your mysql database into all your config files.

**Comment by phil568622** [comment]
@weaondara I think this could be closed, OP isnt responding

**Comment by weaondara** [comment]
jep
