### ISSUE TITLE
Preffix and suffix in bungeeperms 3.0

### ISSUE THREAD

**Issue by xion87** [weaondara/BungeePerms#112]
Prefix and suffix seem brokens with 3.0, not appaering

**Comment by phil568622** [comment]
That's right. Weaondara, when will 3.0 get relaxed?

**Comment by phil568622** [comment]
*released

**Comment by weaondara** [comment]
dev build are available at ci.wea-ondara.net
reguarding *fix i'll take a look at it

**Comment by phil568622** [comment]
@weaondara do you need a Linux Server for automatic builds?
I´ve got a VPS :smile:

**Comment by weaondara** [comment]
i already have one ... see above

**Comment by xion87** [comment]
i tried again the thing, and prefix and suffix dont work and all name and chat is grey

**Comment by xion87** [comment]
Using mineverse chat

**Comment by phil568622** [comment]
Will this issue be fixed? Because I would really need the Prefixes.

**Comment by weaondara** [comment]
i'll take a look tomorrow

**Comment by weaondara** [comment]
if there are any updates see the dev builds

**Comment by xion87** [comment]
any news about this? i want use this but i cant' use because prefix and suffix

**Comment by phil568622** [comment]
This really needs to be fixed SOON!

**Comment by weaondara** [comment]
ok fixed it ... will be at ci soon

**Comment by xion87** [comment]
still dont work for me...
using bungeesuite chat and bungeeperms 3 (from jensin) , it trow this error and chat dont work
http://hastebin.com/xudexamono.avrasm
workin in 2.X

**Comment by metrotyranno** [comment]
Actually it worked for me, only the space of the suffix is not being put in front of it, but behind it, can we have for in front too?

**Comment by weaondara** [comment]
fixed in https://github.com/weaondara/BungeePerms/commit/6ff7d36812bf7f46cda216919ea78c407fe19c03

**Comment by xion87** [comment]
@weaondara did you fix also the thing with bungeesuitechat?

**Comment by weaondara** [comment]
> still dont work for me...
> using bungeesuite chat and bungeeperms 3 (from jensin) , it trow this error and chat dont work
> http://hastebin.com/xudexamono.avrasm
> workin in 2.X

you mean this one?

**Comment by xion87** [comment]
yep!

**Comment by weaondara** [comment]
should be fixed now .. copy paste error
play give it a try and tell me if the problem persists
thx

**Comment by weaondara** [comment]
it's build no 9

**Comment by xion87** [comment]
- suffix dont work, it puted these and end of my tags for use format text for each group....
- libdisguises special permission like libsdisguises.disguise.bat.-setinvisible never worked for me (was working fine with PEX)

**Comment by weaondara** [comment]
do you want to remove the permissions with libsdisguises.disguise.bat.-setinvisible?

**Comment by xion87** [comment]
i want people be able to use disguise and block only setinvisible flag
example
/d bat setinvisible true ---> block this, that permission working fine with pex, and allow the user to use bat disguise with all flags except for invisible one

**Comment by weaondara** [comment]
so you have something like
libsdisguises.disguise.bat.*
libsdisguises.disguise.bat.-setinvisible //remove this

if so use -libsdisguises.disguise.bat.setinvisible

**Comment by xion87** [comment]
and if i use -libsdisguises.disguise.*.setinvisible

**Comment by xion87** [comment]
i added permission libsdisguises.disguise.bat
player cant do /disguise or /disguise bat...

**Comment by xion87** [comment]
there is a similiar issue with this also, http://dev.bukkit.org/bukkit-plugins/skyblock/tickets/345-special-team-permission-dont-work/

**Comment by weaondara** [comment]
can you do a /vault-info and check if bungeeperms appears in the permissions plugin list?

**Comment by weaondara** [comment]
also please give me a list of the permissions list that cause the problem (the whole one)

**Comment by xion87** [comment]
vault-info:
[13:48:41 INFO]: [Vault] Vault v1.5.3-b37 Information
[13:48:41 INFO]: [Vault] Economy: Craftconomy3 [Craftconomy3]
[13:48:41 INFO]: [Vault] Permission: BungeePerms [BungeePerms, SuperPerms]
[13:48:41 INFO]: [Vault] Chat: BungeePerms [BungeePerms]

My permission sql file:
https://mega.co.nz/#!y0IT0I6Q!2PE4zCEJUMSuNIa5giaTR1-Sdb5uB4c0HoS_MAnMT0o

**Comment by weaondara** [comment]
you still have libsdisguises.disguise.bat.-setinvisible instead of -libsdisguises.disguise.bat.setinvisible

**Comment by weaondara** [comment]
also pig, cow, ...

**Comment by xion87** [comment]
i already tried to do the thing of yesterday it do the same thing

**Comment by xion87** [comment]
example i remove  
libsdisguises.disguise.bat.-setinvisible 
and add
libsdisguises.disguise.bat.* --> dont work
libsdisguises.disguise.bat --> dont work
libsdisguises.disguise.* --> work....

**Comment by weaondara** [comment]
but all the other - perms work, right?

**Comment by xion87** [comment]
which ones?

**Comment by weaondara** [comment]
-bungeesuite.homes.commands.sethome
or -mcmmo.ability.*

**Comment by weaondara** [comment]
i can't and libsdisguises.disguise permissions except those -libsdisguises.disguise....

**Comment by xion87** [comment]
all negate permission working fine for me

**Comment by weaondara** [comment]
i'll take a look at the plugin source

**Comment by xion87** [comment]
libdisguises: https://github.com/libraryaddict/LibsDisguises
also take a look about maxteam permmission that is not working with BP tastybento https://github.com/tastybento/askyblock

**Comment by weaondara** [comment]
you use /disgiuse ... right?

**Comment by xion87** [comment]
yeah i use /disguise or /d

**Comment by xion87** [comment]
want join irc chat? so we avoid to spam here http://webchat.esper.net/?nick=&channels=IntellectualCrafters&fg_color=000&fg_sec_color=000&bg_color=FFF

**Comment by weaondara** [comment]
i found the libsdisguises.seecmd.disguise permission seem to be needed

ok

**Comment by HcgRandon** [comment]
No matter what I try I can't get BungeePerms to inject into Vault:

/vault-info
12.06 00:07:19 [Server] INFO Chat: None [null]
12.06 00:07:19 [Server] INFO Permission: SuperPerms [SuperPerms]
12.06 00:07:19 [Server] INFO Economy: None [null]
12.06 00:07:19 [Server] INFO Vault v1.5.3-b37 Information

#server starting
12.06 00:02:07 [Server] INFO Injection of BungeepermsBukkit into Vault
12.06 00:02:07 [Server] INFO Enabled Version 1.5.3-b37
12.06 00:02:07 [Server] INFO [Permission] SuperPermissions loaded as backup permission system.
12.06 00:02:07 [Server] INFO Enabling Vault v1.5.3-b37
12.06 00:02:07 [Server] INFO Injection of BungeepermsBukkit into WorldEdit
12.06 00:02:07 [Server] INFO Injection of BungeepermsBukkit into Vault
12.06 00:02:07 [Server] INFO Activating BungeePerms ...
12.06 00:02:07 [Server] INFO Enabling BungeePerms v3.0-alpha-1

Any ideas @weaondara?

**Comment by xion87** [comment]
any news about the fixing of this bug? :(

**Comment by RustyDesigns** [comment]
Please, this needs to be fixed soon! I love your plugin, this is the only problem.

**Comment by weaondara** [comment]
see  #127
