### ISSUE TITLE
can't get gamemode command to work on all worlds

### ISSUE THREAD

**Issue by DrowArrow** [weaondara/BungeePerms#113]
so i'm trying to get the "**/gamemode (creative/survival) <name>**" command to work and all i seem to be able to do is get it to work on one server using the "**minecraft.command.gamemode**" permission, I've already tried adding the permission to the worlds individually with "**/bp group admin addperm minecraft.command.gamemode servernamehere**", but all i get is you do not have access to this command no matter what I try.. I've even tried adding "**bukkit.command.gamemode**" which is also listed as a permission for that command on the [bukkit wiki for craftbukkit](http://wiki.bukkit.org/CraftBukkit_commands). my bungeeperms config is [here](http://pastebin.com/4KR4abNd), the configs for my worlds are as follows:

Pastebin Links:
* [bobs_Kingdom](http://pastebin.com/MyCFt4Yc)
* [survival](http://pastebin.com/xBV4SxiA)
* [future_world](http://pastebin.com/tmR6bSaC)
* [hub](http://pastebin.com/fu27dt61)

**Comment by weaondara** [comment]
check if you are op on the servers you can use the command

**Comment by weaondara** [comment]
you forgot to obfuscate user and pw in futureworld!

**Comment by DrowArrow** [comment]
ok fixed the mistake on the future world config... as for the matter of being **OP** i'm trying to avoid having to use op out of personal preference so is there any way to achieve success without having to put myself into **OP**... i mean it's got to be possible as the gamemode command works on one of the servers just not the others and i'm not OP on any of them at the moment.

**Comment by DrowArrow** [comment]
@weaondara any more thoughts on this issue?

**Comment by DrowArrow** [comment]
nevermind i appear to have fixed it. thanks for the help anyway.
