### ISSUE TITLE
 migrate backend yalm to mysql2

### ISSUE THREAD

**Issue by k3ldon** [weaondara/BungeePerms#114]
i cannot migrate to msql2...

http://paste.ubuntu.com/10827733/

**Comment by weaondara** [comment]
your mysql settings are invalid (host, password, user, ....)

**Comment by phil568622** [comment]
Are you running the MySQL Server on a linxu vserver with a different ip
than the Minecraft server?

weaondara <notifications@github.com> schrieb am Fr., 17. Apr. 2015 18:30:

**Comment by k3ldon** [comment]
yeap my fault always in the setup be: 

bungeeperms:
  general:
    mysqlpw: 'xxxxx' not xxxx
