### ISSUE TITLE
Are you active?

### ISSUE THREAD

**Issue by phil568622** [weaondara/BungeePerms#116]
Hey, @weaondara.

I just saw your latest commit was 20 Days ago... I think this Plugin is very nice, but I need to ask if you're actively working on this...

**Comment by phil568622** [comment]
Doesnt look like you are

**Comment by weaondara** [comment]
i'm under pressure to do my rl projects so there less to no time for bp ... but i try to keep up

**Comment by weaondara** [comment]
i think i can close this ....
