### ISSUE TITLE
Rank display

### ISSUE THREAD

**Issue by mmxw11** [weaondara/BungeePerms#117]
i think that Display is not working in 3.0 version?

**Comment by weaondara** [comment]
what do you mean by not working?
not showing up?
which environment?
....?

**Comment by xion87** [comment]
using bungeesuite chat and bungeeperms 3 (from jensin) , it trow this error:
http://hastebin.com/xudexamono.avrasm

**Comment by mmxw11** [comment]
I mean i dont see rank in chat but i think i need some chat plugin?

**Comment by weaondara** [comment]
yep bp only provides these settings ...

**Comment by mmxw11** [comment]
Okey problem solved :)
