### ISSUE TITLE
Sponge Plugin

### ISSUE THREAD

**Issue by DunklerPhoenix** [weaondara/BungeePerms#119]
Hi, 
I creating an Server with the SpongeAPI and want to use BungeePerm on it.
Can you Support Sponge please? I tried it with a fork but iam a newbie at java :D

https://docs.spongepowered.org/en/index.html
https://spongepowered.org/

**Comment by weaondara** [comment]
sponge support is on the todo list ... but it will take some time
and currently I have hardly any of it ... sry

**Comment by DunklerPhoenix** [comment]
Thanks this is a good Message ^^

**Comment by SharkROAR** [comment]
A bit out of date, but since I'm now using Sponge as well, I'd love to see it supported :)
