### ISSUE TITLE
Please add sorting to things that are currently unsorted (e.g. permissions).

### ISSUE THREAD

**Issue by moltendorf** [weaondara/BungeePerms#125]
Without sorting, it's almost impossible to determine exactly what sort of setup I have in some situations.

Command output for **/bungeeperms group default list** (for example):

Desired:

```
04:28:45 [INFO] - bungeecord.command.list (own)
04:28:45 [INFO] - bungeecord.command.server (own)
04:28:45 [INFO] - untamedchat.msg (own)
04:28:45 [INFO] - untamedchat.reply (own)
```

**Actual** result:

```
04:28:45 [INFO] - bungeecord.command.server (own)
04:28:45 [INFO] - untamedchat.msg (own)
04:28:45 [INFO] - untamedchat.reply (own)
04:28:45 [INFO] - bungeecord.command.list (own)
```

While this is a small example, it's extremely useful for moderator and admin groups as they can have hundreds of permissions. Even a basic sorting algorithm would greatly improve the usability of this command.

**Comment by weaondara** [comment]
a simple algorythm will break the permission check as permissions are resolved in the order the appear in the list .... be i already thorught about that

**Comment by weaondara** [comment]
done in bp 4
