### ISSUE TITLE
I used Mysql and reloaded, still says no groups?

### ISSUE THREAD

**Issue by TheDigitalToaster** [weaondara/BungeePerms#126]
So I am using bungeecord and Mysql. I made the permissions file, but it says after a reload that there are no groups?

**Comment by phil568622** [comment]
You know that MySQL is?

**Comment by weaondara** [comment]
@phil568622: rofl lol XD
@TheDigitalToaster: permissions file and mysql are different backends ...

**Comment by weaondara** [comment]
ok i'll close this as there is not response ...
