### ISSUE TITLE
fix perms attachement error

### ISSUE THREAD

**Issue by weaondara** [weaondara/BungeePerms#127]
for (PermissionAttachmentInfo perms : player.getEffectivePermissions()) {
		    if (perms.getPermission().startsWith(Settings.PERMPREFIX + "island.maxhomes.")) {
			maxHomes = Integer.valueOf(perms.getPermission().split(Settings.PERMPREFIX + "island.maxhomes.")[1]);

from askyblock

**Comment by xion87** [comment]
any news about this issue?

**Comment by weaondara** [comment]
working on it ... but it's tricking me

**Comment by xion87** [comment]
i know is a so complex plugin but such great :) i will wait and hope

**Comment by weaondara** [comment]
this should be fixed by now

**Comment by xion87** [comment]
which release i should use? there was one but in yellow...

**Comment by xion87** [comment]
i tried to run it on my  test server with jobs plugin and seem it dont block any permission: https://www.spigotmc.org/threads/jobs-reborn.50989/
If i use bungeeperms it:
- give to all user VIP boots about jobs
- no job limit (limit set in config is totaly ignored)

Instead with pex i dont have these issue, could you fix that? (i am sure that is related to this)

**Comment by weaondara** [comment]
i know it's yellow but everything should work as expected ...
i'll write a test for it ...

**Comment by xion87** [comment]
You have skype? so i can comunicate with me more fast and i will help you to debug (i got a test server, that i can give you access) add me xion1987

**Comment by weaondara** [comment]
ok found the problem ... 
i wrote a test plugin .... i can't tell you how much i hate superperms ...
gonna fix it now

**Comment by xion87** [comment]
i tested the permission "libsdisguises.disguise.pig.-setinvisible" it work great! so i think also the perm about skyblock would work fine. But you should fix the compatibility with jobs if you can, i want kick off pex from my faction server :3

**Comment by weaondara** [comment]
which jobs plugin? link pls

**Comment by xion87** [comment]
this one https://www.spigotmc.org/threads/jobs-reborn.50989/

**Comment by weaondara** [comment]
ok, i tested the plugin ...
with default config (just throw jar in plugins folder and start) i have following superperms

```jobs.command.admin.archive
jobs.command.admin.stats
jobs.command.archive
jobs.command.browse
jobs.command.gtop
jobs.command.help
jobs.command.info
jobs.command.join
jobs.command.leave
jobs.command.leaveall
jobs.command.limit
jobs.command.log
jobs.command.stats
jobs.command.toggle
jobs.command.top
jobs.join.brewer
jobs.join.builder
jobs.join.digger
jobs.join.enchanter
jobs.join.farmer
jobs.join.fisherman
jobs.join.hunter
jobs.join.miner
jobs.join.weaponsmith
jobs.join.woodcutter
jobs.use
jobs.world.aflat
jobs.world.alm
jobs.world.estatetest
jobs.world.game
jobs.world.raetia
jobs.world.skyblock
jobs.world.skyblock_nether
jobs.world.skyblock_the_end
jobs.world.world
jobs.world.world_nether
jobs.world.world_the_end```

so i can't see anything abnormal
i'll post a link to a test plugin

**Comment by weaondara** [comment]
jar: http://ci.wea-ondara.net/job/BungeePermsTestSuite/lastBuild/net.wea_ondara$BungeePermsTestSuite/
src: https://github.com/weaondara/BungeePermsTestSuite

**Comment by xion87** [comment]
how i use this?

**Comment by weaondara** [comment]
run /bpts player <your playername> 
and /bpts test superpermslist
all from console and you get a list with all your superperms
look for jobs perms and post them here or via pastebin link or something like that

**Comment by weaondara** [comment]
and please respond to #184 thx
