### ISSUE TITLE
Error dispatching permission check event

### ISSUE THREAD

**Issue by drgnx** [weaondara/BungeePerms#129]
Hey, this is the error I was talking about in my review and reply. I get this message every few seconds, and BungeePerms does not work at all for the users it affects. Problem only starts a few minutes after BungeeCord has already started. We are running the latest version of BungeeCord, and the latest version of BungeePerms.

The issue is similar to this one: https://github.com/weaondara/BungeePerms/issues/52

Stacktrace: http://pastebin.com/M5CXQjAc

List of BungeeCord plugins:
BungeeAdminTools
BungeeController (Custom)
BungeePerms
BungeeTabListPlus
EMPBungee
NameHistory
ServerListPlus
Yamler

**Comment by weaondara** [comment]
sry for the late reply
which version of bp do you use

**Comment by dragonx10101** [comment]
To quote from the post, "the latest version of BungeePerms." Though to be exact, we are using BungeePerms-3.0-alpha-1.

**Comment by weaondara** [comment]
i mean is it a jenkins build

**Comment by dragonx10101** [comment]
Yes, it's the latest Jenkins build.

**Comment by weaondara** [comment]
ok thanks i'll take a look at it

**Comment by lucasdidur** [comment]
I have this error too, did you fix with the last version? Because I have it and getting this error.

**Comment by weaondara** [comment]
is this bug related to #140 ?

**Comment by dragonx10101** [comment]
Maybe? All I know is five minutes after starting the bungee server BungeePerms stops working and BungeeTabListPlus starts spamming errors that it can't hook into BungeePerms.

**Comment by weaondara** [comment]
does this error still our with the new jenkins build?

**Comment by dragonx10101** [comment]
Yes, it's still not fixed.

**Comment by weaondara** [comment]
and now?

**Comment by jimmikaelkael** [comment]
Just have rebuilt BungeePerms this morning from commit 9866a1 and the error is still there...
I only have a few plugins:
- BungeePerms
- BungeeJSON
- BungeeTabListPlus

The error occur as soon as you enable uuid support and it hugely spams the logs.

**Comment by jimmikaelkael** [comment]
I solved the problem on my side. This error seems to be related to a bad use of "uuidplayerdb" in the config. Mine was set to "MySQL2" like the backend type.

After I changed uuidplayerdb to "MySQL" no more error spamming.

**Comment by weaondara** [comment]
jep, thats the problem ... will add a warning at bp boot if not set properly
#192
