### ISSUE TITLE
No prefix/suffix

### ISSUE THREAD

**Issue by jaadava** [weaondara/BungeePerms#130]
Dear,

I migrated the permissions file to the database (MYSQL2),

But if i let a user come online. he just has a white name (default) nothing more.

This is in a test server.

The Bungeecord server runs the following plugins:
- BungeeHub
- BungeePerms [3.0 Alpha-1]

The normal server runs: (spigot 1.8.3)
- BungeePermsBukkit [2.1.2]

Is there a additional plugin needed for it to work or am i doing something wrong?

Thanks,
jaadava

**Comment by phil568622** [comment]
You need to install Vault + a Chat Manager (EssentialsChat works)

Then, when you start your Server, you should see a Vault hooked message

**Comment by phil568622** [comment]
You should also use BungeePerms beta (ci.wea-ondara.net). Its one .jar that can be installed both on Bukkit/Spigot and Bungee. The jar is not stable, although its running very well on my servers

**Comment by jaadava** [comment]
@phil568622  i did what u said, it worked.

Now i've updated my permissions.yml file but how can i send it to the databse?

thanks,

jaadava

**Comment by phil568622** [comment]
You can do it somehow, but I would suggest doing all your edits using commands and with the MySQL2 database as active Backend.

**Comment by jaadava** [comment]
Alright,

Thanks phill568622 for your support, if u wish to see my project all up and running u can visit me on:
play.dutchytcommunity.nl

[Issue closed]
