### ISSUE TITLE
Per server groups

### ISSUE THREAD

**Issue by GingerGeek** [weaondara/BungeePerms#131]
Let's say I run a server network which has a prison and a factions server.
I have "GLOBAL" ranks for staff, donors etc. BUT I also have local ranks e.g prison_L1, prison_L2.
I suppose what I really want is the ability to
/bungeeperms user Bob addgroup SomeGroup SomeServer

**Comment by weaondara** [comment]
are the local ranks used on 1 server only e.g prison groups are only used on prison server
if so just add the permissions,prefixes,etc. per server and add the users to the group

**Comment by GingerGeek** [comment]
say I have two servers on my network: Creative and survival.

Both servers have the rank "trusted". To get Trusted on creative, you must be added by an admin.
On survival you have to donate 4 diamonds. (Custom plugin  handles adding to groups).
Permissions granted include perms for plugins which are on both servers e.g essentials

If I add someoen to trusted on survival, they should still only be default on Creative.

However there are some global ranks e.g "IronDonor" where the rank should be applied network wide.

**Comment by weaondara** [comment]
well then you can create a trusted_creative and trusted_survival group add the permissions per server
so no global perms for them
and the global groups still have global perms

**Comment by GingerGeek** [comment]
You can add group permissions per server?

**Comment by weaondara** [comment]
jep, '/bp group <group> add <perm> [server [world]]'

**Comment by GingerGeek** [comment]
Awesome :+1:

**Comment by weaondara** [comment]
fail lol

**Comment by weaondara** [comment]
wait

**Comment by weaondara** [comment]
jep, '/bp group groupname add perm [server [world]]'

**Comment by weaondara** [comment]
github seems to not like the less than operator

**Comment by lucasdidur** [comment]
I have this error too, did you fix with the last version? Because I have it and getting this error.

**Comment by Hazae** [comment]
So there will be no command for adding to a group on a specific server?

**Comment by dylanweb2** [comment]
I would also love per server groups.

**Comment by dirtyequi** [comment]
Same here. Imho it's not efficient to create different groups with the same permissions for use on different servers.
-> Would love to have per server groups.

**Comment by weaondara** [comment]
currently it's the only way to do it.
i'll think about that idea ... but thats doesn't mean that i'll implement it

**Comment by liamzdenek** [comment]
+1 This is a feature I'm also interested in having.

Right now, I've got several Moderator_[server] groups, and maintaining them is tedious.

An easier approach with a similar outcome than "per server groups" would be to make the assignment of the group have an optional server. Eg:

I create one Moderator group, and assign all required permissions to the group, without limiting the permissions to any specific server. I can `/bp user Test addgroup Moderator`, and they have the permissions of that group on every server. I could `/bp user Test addgroup Moderator creative` and they would only have the permissions of that group on the creative server.

An additional problem I have that this would resolve is the calculation of the primary group for the purposes of chat formatting. If a Moderator_Creative logs in to Prison, I want their chat to be formatted without consideration of their permissions on other servers -- as if they're not in those server specific groups at all -- currently, working around this is complicated and leaves many edge cases where it might not format as desired.

**Comment by weaondara** [comment]
i now like the feature BUT  it's complicated to implement and i'm unsure when this feature will come

**Comment by phil568622** [comment]
+1 would be nice

**Comment by i9hdkill** [comment]
That would be great +1

**Comment by sgdc3** [comment]
+1

**Comment by aurorasmiles** [comment]
Is included in the newest version baff13adb007407a869960916c6b86706a88e9db
