### ISSUE TITLE
Promoting certain people in a ladder

### ISSUE THREAD

**Issue by xaanit** [weaondara/BungeePerms#134]
I'm trying to make it so a rank can promote people in-game from member to any donor rank, but not a rank to a staff rank.

So member to, say, donor. But not member/donor to moderator.

But I can't seem to make it work.

**Comment by weaondara** [comment]
you mean 
mod promotes member -> donor
right?

requirements for the mod group
- 'bungeeperms.promote'
- 'bungeeperms.promote.donorgroupname'
- the rank of the donor group must be lower the the rank og the mod group

and you should be fine
