### ISSUE TITLE
Error using UUIDS on a Spigot server

### ISSUE THREAD

**Issue by Darkcop** [weaondara/BungeePerms#138]
I've recently switched to BungeePerms for my Spigot server, I've set the useUUIDS's to true and saveAllUsers's to false. But now no plugins (Including Spigot) can check the users permissions.

Trying /version from ingame:
https://images.darkcop.co.uk/Dark/xDMHj
 
Trying /list from ingame:
https://images.darkcop.co.uk/Dark/WZFWB
 
Config file:
https://images.darkcop.co.uk/Dark/KhaRb
 
Spigot Version: git-Spigot-044d928-e8c6403 (MC: 1.8.6) (Implementing API version 1.8.6-R0.1-SNAPSHOT)
 
BungeePerms version: 3.0-alpha-1

**Comment by lucasdidur** [comment]
Are you using the latest dev version? I have fixed the same error using the latest.

**Comment by weaondara** [comment]
you can't just set the value to true ... you have to do a migration with the '/bp migrate useuuid true' command
otherwise bp will not be able to find the users as you have experienced
