### ISSUE TITLE
NullPointerException when saveAllUsers = false and you do /bp reload

### ISSUE THREAD

**Issue by lucasdidur** [weaondara/BungeePerms#140]
Hello,

My server has a lot of normal players, to not save all "default users" on database, I have set saveAllUsers to false. So when I do the command /bp reload, all online users has no default group and all plugins get bugged.

To fix this, all users need to relog to pass by onLoginEvent end create a user on a plugin source to save on the users cache. 

Could you fix the command /bp reload to recreate all users who only have a default groups, when saveAllUsers = false is defined.

**Comment by weaondara** [comment]
thanks for the detailed bug report
i'll fix that soon

**Comment by lucasdidur** [comment]
Hello, has not yet been fixed, the correct would be to create a new user in both getUser and not when they sign, because now when I do /bp reload they need to relog to apply the permissions and groups.

**Comment by weaondara** [comment]
does the problem still occur with the latest jenkins build?

**Comment by xion87** [comment]
it happen also with savealluser=true... :(

**Comment by lucasdidur** [comment]
You can review all of this part of saving users the cache and database? It is completely full of problems. I'm having to use a modified version on my server.

**Comment by weaondara** [comment]
related issue #164

**Comment by weaondara** [comment]
this should be fixed in the latest dev-builds
