### ISSUE TITLE
Feature request: divide groups and users in two files

### ISSUE THREAD

**Issue by hazae41** [weaondara/BungeePerms#141]
For better copy/pastability, you should divide groups and users in two files: users.yml where are stored all users and groups.yml where are stored all groups, like GroupManager.

This scenario often happens: I have a big network, more than 200 players connected, the changes in permissions.yml quickly occurs (about 1 to 10 changes per minute). When I want to manually change a thing in the groups, I do it and save. But between the download of the file and the upload, we got up to 20 changes of the users made by the server that are erased due to the editing of the groups.

So you could really divide them.

**Comment by weaondara** [comment]
why don't you use mysql2 as backend? 
i strongly recommend it for bigger networks 
- less memory usage
- better performance
- better editablility

**Comment by weaondara** [comment]
impl in 529fa758845a3978aa9a7
