### ISSUE TITLE
Prefix Support: Nonexistent

### ISSUE THREAD

**Issue by RustyDesigns** [weaondara/BungeePerms#146]
I have herochat, vault, and your plugin configured correctly. I still do not get any prefixes. I believe this is on the plugin side of error.

Group Info: https://infinit.io/_/3aL3ZFi
When I Chat: https://infinit.io/_/3pSi6hV

**Comment by weaondara** [comment]
check the group info on bukkit with the info command
check bungeeperms vault-chat integration with /vault-info; bungeeperms should be mentioned in the chat section

if all that seems right please comment here

**Comment by tssge** [comment]
I can confirm. Here's Vault info: http://i.imgur.com/wGsGEed.png

**Comment by tssge** [comment]
Updating to the newest dev build in Jenkins seemed to fix the issue.

**Comment by phil568622** [comment]
Download the newest Version at ci.wea-ondara.net and put it in your bungee and bukkit plugins folder. Delete BungeePermsBukkit if you still have it installed in your Server.

**Comment by phil568622** [comment]
Okay. You should close the Issue

**Comment by tssge** [comment]
Not my issue, but @RustyDesigns can close it when he sees these comments.

**Comment by weaondara** [comment]
is fixed in latest dev-builds
