### ISSUE TITLE
permissions issue and connection issue

### ISSUE THREAD

**Issue by Dominikzocker141** [weaondara/BungeePerms#148]
Error authorization abbreviation For example:
'*'
essentials.chat. *
and at the connection between bungeecord and spigot, after entering the permissions when updating the authorization database.
Please fix !!

**Comment by weaondara** [comment]
i'm sorry but can you explain it in more detail?
thx

**Comment by weaondara** [comment]
von mir aus auch auf deutsch

**Comment by Dominikzocker141** [comment]
Wenn ich die berechtigungen auf einem von Servern ingame eingebe akzepiert nur der bungeecord und der server wo ich drauf bin die berechtigungen und die anderen server nicht automatisch, um den fehler zu beheben muss ich die Server neustarten um den fehler zu beheben. 
Es gibt auch keine verständigung laut dem debug modus mit der mysql datenbank und den anderen Servern wo ich nicht connectect bin dabei.
Außerdem nimmt das plugin die berechtigungen von der offiziellen seite von spigot und bukkit 
nicht an:
https://www.spigotmc.org/wiki/spigot-commands/
http://wiki.bukkit.org/CraftBukkit_commands

mann kennt ja sicher das recht mit dem * bei pex das alle rechte hergibt.
wenn ich in bungeeperms das eingebe zeigt es keine wirkung.
z.b. siehe ausschnitt unten (von pex) unter permissions.
(das meine ich)

 Admin:
   default: false
   prefix: 'Admin'
   suffix: ' '
   permissions:
   - '*'

(Gerne können wir auch über skype Reden.
Mein Nickname ist in skype Dominikzocker141)

**Comment by weaondara** [comment]
wie sieht denn die configuration aus?
wenn du mehere server hast solltest du mysql2 als backend und mysql als uuid-player-db verwenden
die mysql anmelde daten sollten überall die gleichen sein
desweiteren empfehle ich auf uuid authentication zu gehen

um backend use-uuid und uuidplayerdb zu wechseln solltest du den '/bp migrate' command verwenden .... aber nur auf einem server eingeben und bei den anderen die config entsprechend anpassen 
danach kompletter restart
