### ISSUE TITLE
groups on different world

### ISSUE THREAD

**Issue by CraftYourWay** [weaondara/BungeePerms#149]
for example i have 4 servers

and all servers need a rank
is there a way so that when i enter for example skyblock i get the rank skylanders and when i go to my creative world i get the rank builder, i dont want one user with 4 ranks at the same time i want one user that gets a differend rank everytime it changes a server, this because of inventory problems and other problems

**Comment by weaondara** [comment]
groups are always global

what you can do:
add the 4 groups to each user
add the permissions to a group on one server only; so skyblock permission on skyblock only and vice versa; this is also possible for permissions
