### ISSUE TITLE
BungeePermsBukkit not working

### ISSUE THREAD

**Issue by brainscript** [weaondara/BungeePerms#151]
When I create a group using `bp group Owner create`, add all permissions using `bp group Owner addperm *` and assign myself to that group using `bp user brainscript setgroup Owner`, I can do `server mr1` to connect to one of the MinersRush servers. But when I trie `gm 1` on that server, it says `You don't have permission.`. I'm using BungeeCord snapshot `81d1c46` and Spigot version `git-Spigot-6d0ae89-a03743b (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)`. Of BungeePerms I'm using `3.0-alpha-1`, but I also tried older versions and of BungeePermsBukkit I'm using `2.1.2`.

I only have installed `CleanroomGenerator`, `MiningTNT`, `WorldEdit`, **`BungeePermsBukkit`**, `EditableSign`, `PlugMan`, `FarmProtect`, `Tablist`, **`Vault`**, **`CommandBook`**, `Multiverse-Core`, `Denizen`, `Depenizen`.

My configs look like this on the BC: *I removed all unimportant values.*
`useUUIDs: true`
`useregexperms: false`
`grouppermission: true`
`backendtype: MySQL2`
`uuidplayerdb: MySQL2`
`tablePrefix: bp_`
`bungeeperms:`
`--general:`
`----mysqlhost: localhost`
`----mysqlport: '3306'`
`----mysqldb: mc_perms`
`----mysqluser: root`
`----mysqlpw: r4nd0mPW`
`uuidfetcher:`
`--cooldown: 3000`
`saveAllUsers: true`
`deleteUsersOnCleanup: false`
`cleanup:
`--interval: 1800
`--threshold: 600`
`networktype: Global`
`networkservers: []`

... and like that on the Bukkit/Spigot:
`servername: mr1`
`allowops: false`
`debug:`
`--path: plugins\BungeePermsBukkit/debug.log`
`--showexceptions: true`
`--showlogs: false`
`backendtype: MySQL2`
`tablePrefix: bp_`
`bungeeperms:`
`--general:`
`----mysqlhost: localhost`
`----mysqlport: '3306'`
`----mysqldb: mc_perms`
`----mysqluser: root`
`----mysqlpw: r4nd0mPW`

Please help ... @weaondara @CodeCrafter47

**Comment by CodeCrafter47** [comment]
uuidplayerdb needs to be set to MySQL not MySQL2. You also need to set that value on bukkit/spigot.

If you use version 3.0 of BungeePerms you shouldn't combine it with BungeePermsBukkit 2.1.2 but put the same BungeePerms.jar file on spigot as you use on BungeePerms.

**Comment by RustyDesigns** [comment]
Your problem is that you need to replace BungeePermsBukkit with BungeePerms, bungee perms bukkit is now longer needed, and is build into BungeePerms.

**Comment by brainscript** [comment]
Ok, I'll try it, because since I'm using the alpha version, this bug appears: https://github.com/SpigotMC/BungeeCord/issues/1441

**Comment by brainscript** [comment]
Jayyy, it works now! :smiley:  And the bug is gone. :bug: Please add an installation tutorial in the wiki on how to setup the connection between BC and Spigot. :book:

When I'm done with the German translation, I'll give it to you as a liitle gift. :balloon:
