### ISSUE TITLE
Permissions gehen nicht

### ISSUE THREAD

**Issue by MiniMinerLPs** [weaondara/BungeePerms#152]
Hello,

sorry for my english... -.-

bungeecord and bungeepers permissions are working, but all the other not... do I need a MySQL Database and BungeePermsBukkit? Where can i setup the database? (Name, PW, etc.)
In the discription of BungeePermsBukkit stands that it's not longer supported... idk

**Comment by MiniMinerLPs** [comment]
I also get this Error when i restart BungeeCord;

14:38:48 [SCHWERWIEGEND] java.lang.IllegalStateException: config failed to load; save not allowed
14:38:48 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.Config.save(Config.java:59)
14:38:48 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.Config.getString(Config.java:95)
14:38:48 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.Lang.load(Lang.java:21)
14:38:48 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.BungeePerms.load(BungeePerms.java:62)
14:38:48 [SCHWERWIEGEND] 	at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:61)
14:38:48 [SCHWERWIEGEND] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:302)
14:38:48 [SCHWERWIEGEND] 	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:205)
14:38:48 [SCHWERWIEGEND] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:247)
14:38:48 [SCHWERWIEGEND] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54)
14:38:48 [SCHWERWIEGEND] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by phil568622** [comment]
Okay, eine kleine Zusammenfassung. Ja, du brauchst eine Mysql-Datenbank. Du lädst dir die NEUSTE Version von ci.wea-ondara.net/job/BungeePerms/lastSuccessfulBuild/ herunter, und ziehst diese in den Plugin-Ordner von BUKKIT UND BUNGEE. Das Plugin beinhaltet sozusagen 2 Plugins, ein BUKKIT und ein BUNGEE Plugin. Nun löschst du alle Bungeeperms-Config-Ordner und stellst bei BEIDEN config-dateien jeweils deine mysql-daten ein. 

Außerdem solltest du mal einen Blick auf deine Dateisystem-Rechte werfen, es sieht so aus als könnte der User mit dem der Server gestartet wird nicht in das richtige Verzeichnis schreiben, weil er keine Rechte hat.

**Comment by MiniMinerLPs** [comment]
Mit den Userrechten stimmt eig. alles... :o Ich probiers mal aus ^^

**Comment by MiniMinerLPs** [comment]
Die Sache ist, dass ich in der Config nur tablePrefix: bungeeperms_ finde und nichts von user password etc. wo finde ich das?

**Comment by MiniMinerLPs** [comment]
?

**Comment by MiniMinerLPs** [comment]
Ah, musste von YAML auf MySQL stellen... jetzt sagt er "The player does not exist"

**Comment by MiniMinerLPs** [comment]
Nachdem ich es jetzt auf MySQL umgestellt habe und MySQL funzt, kommt, wenn ich bei der BungeeCord Konsole "bungeeperms promote miniminerlps" eingebe " 19:52:30 [INFORMATION] The player MiniMinerLPs doesnt have a group! "

und, wenn ich es auf meinem Bukkitserver eingebe dieser Error:

bungeeperms promote miniminerlps
>
[19:50:26 WARN]: Exception in thread "pool-3-thread-4" 
>
[19:50:26 WARN]: org.apache.commons.lang.UnhandledException: Plugin BungeePerms v3.0-alpha-1 generated an exception while executing task 70
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin.onCommand(BukkitPlugin.java:103)
        at net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin$1$1.run(BukkitPlugin.java:139)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:53)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

>

**Comment by MiniMinerLPs** [comment]
So, funktioniert jetzt... ich hab es auf MySQL2 gestellt. Das Plugin braucht auf jeden Fall mal ein Videotutorial! Ich bin wahrscheinlich nicht der einzige, der das ganze checken muss... Kann ich ein Video machen und es euch schicken, sodass ihr es in eure Spigot Seite, etc. einbinden könnt?

**Comment by phil568622** [comment]
Sehr schön. Ich bin zwar nicht der Entwickler, aber @weaondara wird es sicher einbinden.

**Comment by MiniMinerLPs** [comment]
Dann werde ichs machen! Jetzt noch eine Sache: Wann werden die Farben mit den Prefixen gehen?

**Comment by phil568622** [comment]
Ich weiß nicht, bei mir gehen die Color Codes in den Prefixen. Probiers mal mit nem anderen chatmanager. Außerdem muss auf jedem spigot-server auch BungeePerms mit der Datenbank installiert sein

**Comment by MiniMinerLPs** [comment]
@phil568622 Kannst du mir einen empfehlen? Ausser Essentials :P

**Comment by MiniMinerLPs** [comment]
Alles andere geht.

**Comment by weaondara** [comment]
hast du die vault integration gecheckt mit /vault-info?

**Comment by phil568622** [comment]
@weaondara bist' du ein Deutscher? :O

**Comment by weaondara** [comment]
-

**Comment by MiniMinerLPs** [comment]
So @weaondara  : I've made a german Tutorial. Could you please integrate this Tutorial: https://www.youtube.com/watch?v=Mb4SmSBeARw in your spigotmc.org Thread? Would be very nice!

**Comment by weaondara** [comment]
added
