### ISSUE TITLE
Offline UUID Support

### ISSUE THREAD

**Issue by ScriptJunkieMC** [weaondara/BungeePerms#154]
Needs support to tie into a plugin like AlwaysOnline or have it integrated. When mojang goes offline the whole system crashes to a hault.

**Comment by CodeCrafter47** [comment]
You probably want to report this bug to AlwaysOnline too.

In theory it should work because AlwaysOnline updates the players uuid to the online mode uuid. But it doesn't work because BungeePerms accesses the uuid before AlwaysOnline sets the correct uuid.

**Comment by weaondara** [comment]
it's a known issue of always online
i'll try to fix that soon

**Comment by ScriptJunkieMC** [comment]
I have moved to neverdownproxy and seems to work better at this point.

**Comment by weaondara** [comment]
well always online uses bad event priorities ... -64 instead of -128
so thats an issue of always online and not a bp fault
