### ISSUE TITLE
Player join

### ISSUE THREAD

**Issue by pricey123** [weaondara/BungeePerms#155]
Whenever a player joins my server the console fills with spam.
I have the plugin added to both Bungee and Spigot, and both are connected to the same mysql db.
The Bungee console seems fine, however the Spigot console fills with spam.
Log: http://pastebin.com/c1Xadcb5

**Comment by pricey123** [comment]
The player join error starts at around line 579.

**Comment by CodeCrafter47** [comment]
Does this also happen with the latest dev-build?

**Comment by pricey123** [comment]
Yes

**Comment by CodeCrafter47** [comment]
But your log shows you are using the build from spigot website on your spigot server, not the dev-build from jenkins.

However I think this is probably a configuration issue. Can you provide the config files you use on bungee and spigot?

**Comment by pricey123** [comment]
http://pastebin.com/Zrdwq4PK
I am using the version from jenkins.

**Comment by CodeCrafter47** [comment]
On bungee you have useUUIDs false but on spigot it is true. It should be the same. If you want it to be true you should also set uuidplayerdb to MySQL.

**Comment by pricey123** [comment]
What should the config look like if i was to set a db for that?

**Comment by CodeCrafter47** [comment]
Either you have
```
useUUIDs: true
uuidplayerdb: MySQL
```
or
```
useUUIDs: false
uuidplayerdb: None
```
on both servers. If you already setup permissions without using uuids you can use the /uuid migrate command on one server before changing the config files on all servers.

**Comment by pricey123** [comment]
Even after making the changes you have said, I still get the errors when ever a player joins.

**Comment by CodeCrafter47** [comment]
Maybe you could download the latest jenkins build and put it on your spigot servers to make sure you really have the latest version of the plugin.

**Comment by pricey123** [comment]
Still occurs

**Comment by CodeCrafter47** [comment]
Are you sure you have set `uuidplayerdb: MySQL` on every server.

**Comment by pricey123** [comment]
Yes im sure i have that set

**Comment by weaondara** [comment]
looks like a missconfiguration
common faults:
- you set useuuid to true in the config
- no uuid player db
