### ISSUE TITLE
Api?

### ISSUE THREAD

**Issue by mmxw11** [weaondara/BungeePerms#156]
I think it would be good if i can get player ranks via api in another plugin.

E.g: Groups.getPlayerRank(String UUID);

**Comment by weaondara** [comment]
BungeePerms.getInstance().getPermissionsManager().getUser(uuid).getGroups()

**Comment by mmxw11** [comment]
Oh, thanks :)

**Comment by mmxw11** [comment]
hmm how i close this issue :D
