### ISSUE TITLE
Groups not updating until plugin is reloaded - Using MySQL

### ISSUE THREAD

**Issue by Dakotaa** [weaondara/BungeePerms#159]
I have all of my servers' backends set to the same MySQL database, but when I add myself to a group in the hub server and go to another server, it does not update and I need to do /bp reload to get the group I added to myself on the hub server to show up on the server I joined.

**Comment by weaondara** [comment]
is bungeeperms configured as standalone?

**Comment by RustyDesigns** [comment]
What do you mean "a standalone"?

**Comment by weaondara** [comment]
if bp runs on its own or if it forms a network
config settings
