### ISSUE TITLE
No Permissions

### ISSUE THREAD

**Issue by RustyDesigns** [weaondara/BungeePerms#160]
I have the '*' permission, with the '' around it, and I can't preform bungeeperms commands.
Why is this?

**Comment by phil568622** [comment]
Download the newest Version of BungeePerms from ci.wea-ondara.net and reset your config. This jar can be installed on Spigot and BungeeCord Servers! You should use "MySQL2" as Database and "MySQL" as UUID Database!

**Comment by weaondara** [comment]
related #162
