### ISSUE TITLE
BungeePerms Permission

### ISSUE THREAD

**Issue by RustyDesigns** [weaondara/BungeePerms#162]
I can do anything but the native bungeeperms commands? Why? I have permissions to do so. https://infinit.io/_/mMaNXjC

**Comment by phil568622** [comment]
Is rustycore a bukkit or bungee Plugin?

**Comment by RustyDesigns** [comment]
Bukkit.

**Comment by phil568622** [comment]
Okay, BUNGEECORD has its OWN permission system. 

https://www.spigotmc.org/wiki/bungeecord-configuration-guide/

You need to run "/bp user yourname add *" from your BUNGEECORD Console.

**Comment by RustyDesigns** [comment]
I have a that, I can run almost any command, just not any of the command native language to BungeePerms

**Comment by RustyDesigns** [comment]
What does this mean? http://pastebin.com/t6S6VGkS

**Comment by phil568622** [comment]
-_-

You NEED to configure MySQL!  I hope you know how to do this...
