### ISSUE TITLE
standalone reload bug

### ISSUE THREAD

**Issue by weaondara** [weaondara/BungeePerms#164]
enn man die standalone version nutzt und nen reload macht, werden bei allen usern die gesetzten ränge entfernt bis auf die default gruppe
allerdings sind die nach nem relog wieder da

**Comment by brainscript** [comment]
@weaondara Bei mir werden bei einem Reload die Ränge aus der YML-Datei und nicht wie eingestellt aus der Datenbank geladen. Nach einem Restart werden die Ränge wieder richtig geladen.

**Comment by weaondara** [comment]
on bungee and bukkit

**Comment by weaondara** [comment]
@brainscript besteht das problem noch immer?
wenn ja mal /bp migrate backend eingeben und nachschaun obs passt

**Comment by weaondara** [comment]
fixed in latest dev-builds
