### ISSUE TITLE
Suffixes Not Working

### ISSUE THREAD

**Issue by sammyg7241** [weaondara/BungeePerms#165]
I have the plugin installed and setup, along with vault but can't get the suffixes to chow in my chat.

**Comment by phil568622** [comment]
Please give me the output from /vault-info and /pl.

**Comment by sammyg7241** [comment]
http://imgur.com/krHRb2b

**Comment by weaondara** [comment]
well, seems like bp is not used by vault

**Comment by weaondara** [comment]
you have pex installed on that server ...
