### ISSUE TITLE
Einige kleine Bugs

### ISSUE THREAD

**Issue by brainscript** [weaondara/BungeePerms#166]
@weaondara *Leider habe ich gemerkt dass du in letzter Zeit sehr inaktiv auf GitHub warst, was man dir grundsätzlich nicht übel nehmen kann. Aber es warten nunmal schon einige Issues darauf von dir gelesen und entsprechend beantwortet bzw. gefixt zu werden. Ich weiß nicht ob du grade einfach nur keine Lust auf Minecraft :cactus: hast, viel zu tun hast oder auf dem Klo sitzt :toilet::smile:.*
*Wie auch immer: Ich hoffe dass du dich bald wieder um meine und die Issues der anderen kümmerst, denn dein Plugin ist einfach einzigartig auf SpigotMC und zusammen mit  @CodeCrafter47 's [BungeeTabListPlus](https://www.spigotmc.org/resources/bungeetablistplus.313/) einfach die beste Lösung für Rechte und die Tablist.*

So jetzt aber zur Bugliste:
- [x] Wenn ein Spieler z.B. durch das Beenden des Lobbyservers oder durch eine aktivierte Whitelist bei Wartungsarbeiten vom Netzwerk gekickt wird, **hängt sich BungeePerms auf, der BungeeCord friert ein (wodurch alle Spieler im Netzwerk nach einiger Zeit gekickt werden)** und in der Serverliste werden immer noch alle Spieler angezeigt, man kann aber nicht mehr joinen.
- [x] Wenn ein Plugin, in meinem Fall die Skriptsprache [Denizen](https://github.com/DenizenScript/Denizen-For-Bukkit) eine Nachricht an alle Spieler mit `Bukkit.getServer().broadcastMessage("NACHRICHT")` schickt, dann sehen diese **nur Spieler mit OP**
- [x] Der Befehl `/bp reload` lädt die Rechte **nicht wie angeben** aus der MySQL-Datenbank sondern aus der YAML-Datei.
- [x] Allgemein könnte die Synchronisation verbessert werden. Wenn ich den BungeeCord beende sind die Gruppen manchmal **noch nicht gespeichert** und wenn ich einer Gruppe Rechte auf einem bestimmten Server zuweise dauert dies manchmal **Ewigkeiten bis diese endlich übernommen sind**, aufgrund des bei Punkt 3 beschriebenen Fehlers ist es dann auch **nicht möglich diese neuzuladen**.

**Diese Bugs machen das Plugin für mein Servernetzwerk leider nutzlos ...**
**... deshalb würden sich mein Team und ich sehr freuen wenn du die Bugs fixen würdest.**

**Comment by weaondara** [comment]
thx, für die reports ... bin immer stark ausgelastet daher passiert nicht viel

**Comment by CodeCrafter47** [comment]
Ich bin gerne bereit ein wenig zu helfen, damit Fehler schneller behoben werden.

**Comment by brainscript** [comment]
@weaondara Ich hab mich grade gewundert, wieso @CodeCrafter47 noch keinen Rang hier hat. Ich denke sein Plugin BungeeTablistPlus und seine hier eingereichten Pullrequests beweisen eindeutig dass er das Zeug hätte hier auch fest mitzuarbeiten.

Das Plugin ist nun mal in seinem Funktionsumfang echt **einzigartig** auf SpigotMC, kann aber aufgrund der oben genannten Bugs derzeit **nicht produktiv eingesetzt** werden. Ich habe aber keine Lust umständlich (wie Timolia) PEX zu verwenden, obwohl dies an sich gar nicht für Netzwerke gedacht ist und nur durch umbenennen der Serverwelten ein solcher Effekt erzielt werden kann.

**Comment by brainscript** [comment]
@weaondara @CodeCrafter47 Irgendwelche Neuigkeiten? Habt ihr euch schon drangesetzt die Bugs zu fixen? Ich will euch nicht stressen, ist ja eure Freizeit, aber BungeePerms ist derzeit das **einzigste Problem** was uns daran hindert unsere Servernetzwerk in die OpenBeta zu entlassen, da der BungeeCord so **nicht stabil läuft** und sich **häufig aufhängt** und schließlich abstürzt.

Bitte kümmert euch schnellstmöglich um die Behebung der Fehler. **MfG brainscript** :smile:

**Comment by CodeCrafter47** [comment]
@brainscript Ich finde du bist manchmal ziemlich unhöflich. @weaondara entwickelt dieses großartige Plugin in seiner Freizeit. Und er hat auch noch andere Dinge zu tun. So dauert es eben manchmal etwas länger bis Fehler behoben sind. Sich ständig darüber zu beschweren hilft nicht weiter.

Im übrigen konnte ich deinen ersten Bug nicht reproduzieren, und ich denke dein zweiter Bug ist eher ein Konfigurationsfehler (es gibt, oder gab es jedenfalls früher, irgendwelche Broadcast Permissions die man braucht um Broadcasts zu sehen, schau einfach mal im Bukkit Wiki).

**Comment by weaondara** [comment]
nr 1: besteht der fehler in dem latest dev build noch immer?
nr. 2: sollte behoben sein in den dev-builds
nr. 3: nach einem /bp reload bitte /bp migrate backend ausführen und schaun ob das backend mysql2 ist
nr. 4: bp speichert immer instant und notified die server im bp netzwerk falls bp nicht auf standalone ober mit limiterten netzwerk läuft

**Comment by brainscript** [comment]
@weaondara Ich habe mein Netzwerk nun wieder komplett von PermissionsEx auf BungeePerms umgestellt. Es funktioniert jetzt auch alles wieder großartig. Und da du jetzt das Plugin auch wieder weiterentwickelst, werden wir dieses Plugin auch weiterhin verwenden! :smile:

**Comment by weaondara** [comment]
schön
