### ISSUE TITLE
Bungeeperms Bukkit

### ISSUE THREAD

**Issue by Pl4ntnet** [weaondara/BungeePerms#169]
Hallo!
Ich würde gerne bungeeperms auch auf dem bukkit/spigot Server laufen lassen, aber ich finde zu der bukkit bridge keinen download!
Wäre cool wenn du mir sagst wo ich das downloaden kann! (:

**Comment by CodeCrafter47** [comment]
Du kannst die Datei die du von der Spigot Webseite herunterlädst sowohl für BungeeCord als auch für Spigot/ Bukkit verwenden.
