### ISSUE TITLE
Prefix Anzeige

### ISSUE THREAD

**Issue by Pl4ntnet** [weaondara/BungeePerms#170]
Hallo,
ich bins nochmal :D
Ich habe BungeePerms auf 2 Servern + Bungeecord laufen (und verbunden). Soweit funktioniert alles!
Aber komischerweise wurde der Prefix von einer auf die nächste Minute nicht mehr angezeigt (benutze Essentials).
Würde gerne mal wissen woran das liegen könnte (kommt auch keine Fehlermeldung im Log etc)!
Wie gesagt, habe nichts ausergewöhnliches gemacht, außer ein paar configs einzustellen.
Sag bitte bescheid, falls du eine Config.yml brauchst oder so!

LG 
Bitte schreibe baldmöglichst :)

PS: Gibt es ein kompatibles Plugin außer Essentials das den Prefix von BungeePerms anzeigen kann? 
Wäre nice wenn es etwas für BungeeCord gäbe (wegen Global Chat)

**Comment by brainscript** [comment]
@Pl4ntnet https://www.spigotmc.org/resources/bungeetablistplus.313/

**Comment by Pl4ntnet** [comment]
@brainscript Das kenne ich schon, aber danke :)
Aber ich dachte an ein Chat Plugin ;).

**Comment by brainscript** [comment]
@Pl4ntnet Kenn grad keins.

**Comment by Rustypredator** [comment]
FreeBungeeChat https://www.spigotmc.org/resources/freebungeechat.1617/
Scheint zu funktionieren, hat auch global chat. habe die prefixe aber bisher nur auf einem server ohne bungeecord zum laufen bekommen.
Da du mehrere hast, hast du das selbe problem wie ich :D der prefix wird als "undefined" angezeigt.
Ich habe bei dem chat plugin schon gefragt ob es da ein problem gibt. werde updaten bei neuigkeiten

**Comment by weaondara** [comment]
besteht der fehler noch immer mit den latest dev build?

**Comment by weaondara** [comment]
jetzt sollte es sicher gehen

**Comment by Rustypredator** [comment]
wenn ich den server zum starten bekomme ( #196 ) kann ich es dir sagen...

**Comment by Rustypredator** [comment]
Mit der neuesten version funktioniert es jetzt. ( habs mit free bungee chat versucht )
kann meiner meinung nach geschlossen werden
