### ISSUE TITLE
Using /bp group xxx info results in NullPointerException

### ISSUE THREAD

**Issue by zedwick** [weaondara/BungeePerms#173]
Entering that, or other commands, results in the following error:

https://pste.me/#/6MPEa

Above is specifically just from running "/bp group Guardian info"

Command does not run.

Appears both when running the beta 3.0 alpha 1 jar available, and when built from the latest in github.

**Comment by Ollie262** [comment]
I have to use console to promote people, cannot use commands for promotion in game..

**Comment by zedwick** [comment]
This issue was due to a couple of capital 'y' in my config.

MYSQL should be MySQL. Quite the picky plugin ya got there.
