### ISSUE TITLE
vault support and negating permissions

### ISSUE THREAD

**Issue by popcorn9499** [weaondara/BungeePerms#174]
I was wondering how to do this but i have noticed bungeeperms is missing vault support. This means that my plugins that you need to do something to get there dont work and also i have found negative permission nodes to be really kinda strange.

I was wondering if u can fix these things.
If u need more things to go one tell me.

**Comment by CodeCrafter47** [comment]
Vault support see #176 .

Can you make an example of negative permission nodes behaving in a strange/ unexpected way?
