### ISSUE TITLE
Fix bungeeperms to avoid high load on Bot Attack

### ISSUE THREAD

**Issue by Phreag** [weaondara/BungeePerms#177]
When my Server is under Attack by Bot-Kiddies bungeeperms produces a lot of load by adding default groups to all bots.

If it would ignore cancelled login events it would be great....

**Comment by weaondara** [comment]
should be fixed in a05a212
bungeeperms handles login event at prio 1 ... so cancelling at prio 0 should be possible

**Comment by Phreag** [comment]
grad gesehen dass du deutsch sprichst :P
Gibt es von Bungeeperms irgendwo einen Build-Server? Weil wenn ich das Maven Projekt in Eclipse importiere hat der ca 1100 Fehler und ich hab kp wieso.
Oder muss ich da eine andere IDE verwenden damit das funzt?

**Comment by weaondara** [comment]
ci ja -> ci.wea-ondara.net, 
artifact nein ... leider

**Comment by CodeCrafter47** [comment]
http://ci.wea-ondara.net/job/BungeePerms/lastBuild/net.alpenblock$BungeePerms/ ?
