### ISSUE TITLE
Not syncing between multiple servers.

### ISSUE THREAD

**Issue by Ollie262** [weaondara/BungeePerms#178]
I am trying to get the permissions file to sync between multiple servers. I can only get them to work on them individually which makes promoting players hard. Especially when I am the only one who has access to do it on the bungecord console(so no one can use /server etc.). 

Could someone explain why or give me a run through of how to do this.

Thanks.

**Comment by CodeCrafter47** [comment]
The permission.yml file is never synced. You should only use the yaml backend if you only run BungeePerms on the proxy. If you want BungeePerms to sync permissions across your network you should use a mysql database for the permissions.

**Comment by weaondara** [comment]
yep ...

**Comment by Ollie262** [comment]
I have 2 servers and bungeecord up, but I try and set the perms for a player and it only sets per server. Therefore the ones on bungeecord server do not get set stopping them using bungeecord commands.

**Comment by weaondara** [comment]
please post your configs
