### ISSUE TITLE
Question / Per server permissions

### ISSUE THREAD

**Issue by punnydoge** [weaondara/BungeePerms#179]
I have a question. Lemme see if I can make this easier to understand 'cuz my brain was developed unbelievably weird and my questions sometimes make little sense. xD

If I set up a default group like below, and then add rank NEW to server 2 which inherits default, will rank NEW inherit only perm.2, or will it inherit perm.1 and perm.2 Thanks! 

I think I have got per-server permissions to work, but inheritances are giving me trouble  T_T. If group Default has permissions for server 1:, and there's a second group called Player which inherits Default, it seems to only inherit the main permissions, not the server 1: permissions. Am I doing something incorrectly? Can't seem to get a group to inherit the server-specific permissions of it's parent group, only the main permissions of said group.

http://pastebin.com/jqF8PF1N

**Comment by punnydoge** [comment]
I think I have got per-server permissions to work, but inheritances are giving me trouble now T_T. If group Default has permissions for server 1:, and there's a second group called Player which inherits Default, it seems to only inherit the main permissions, not the server 1: permissions. Am I doing something incorrectly?

**Comment by CodeCrafter47** [comment]
I think the issue does happen because you write default once and Default another time. Decide for one name for the group and everything will work well.

**Comment by punnydoge** [comment]
I think that was exactly it, it's case-specific, thank you!
