### ISSUE TITLE
Primary Group confusion

### ISSUE THREAD

**Issue by punnydoge** [weaondara/BungeePerms#183]
http://pastebin.com/eft3EjDy

If I'm in group Default, and I addgroup B, the prefix for B does not override Default. Could someone please point out what am I doing incorrectly? Thanks!

**Comment by weaondara** [comment]
you are doing nothing wrong ... i should be like that

**Comment by punnydoge** [comment]
I see..is there any way I can configure it so Group B overrides Group Default? Default should be lowest weight, when I addgroup B, I want B prefix to show, not Default prefix.

**Comment by weaondara** [comment]
group b inherit from default group
add group b and remove group default

**Comment by punnydoge** [comment]
@weaondara Technically that would work, however, I NEED group Default, since there are no per-server Groups. 

http://pastebin.com/eft3EjDy     
-if you check this now, I have added group C inherit from group B to config.

If I addgroup B, removegroup Default, [B] prefix shows
Now I addgroup C but I DO NOT removegroup B, and C shows.

C takes priority over B, but B does not take priority over Default. Either I am doing something wrong, or there's a bug, I must assume.

**Comment by weaondara** [comment]
no it works as expected ... all prefixes are put together ...
there's only the one way ... only have 1 group at a time
