### ISSUE TITLE
jobs reborn perm fail

### ISSUE THREAD

**Issue by weaondara** [weaondara/BungeePerms#184]
see #127

**Comment by weaondara** [comment]
file in question: https://github.com/Zrips/Jobs/blob/master/com/gamingmesh/jobs/commands/JobsCommands.java

**Comment by xion87** [comment]
- is not fixed, tried now
- plugin: Jobs, vault, essentials-x,bungeeperms
- configure generalConfig.yml with max-jobs: 1 and start the server
- Join with a random player no permission on it
- type /jobs browse and join alchemy, i can join every job with having all jobs available in same moment....

**Comment by xion87** [comment]
can you join my test server?

**Comment by weaondara** [comment]
you have the perms list

**Comment by weaondara** [comment]
ok i try that config

**Comment by weaondara** [comment]
there's no alchemy

**Comment by xion87** [comment]
join one of the jobs available then, notice that you can have all jobs without job cap

**Comment by xion87** [comment]
my perm list http://hastebin.com/leqarisiyo.avrasm

**Comment by weaondara** [comment]
well same here ... just looked into the source of jobs ... either the plugin has some bugs or i'm wrong but
```
int confMaxJobs = ConfigManager.getJobsConfiguration().getMaxJobs();
	short PlayerMaxJobs = (short) jPlayer.getJobProgression().size();
	if (confMaxJobs > 0 && PlayerMaxJobs >= confMaxJobs && !Jobs.getPlayerManager().getJobsLimit(pSender, PlayerMaxJobs)) {
	    sender.sendMessage(ChatColor.RED + Language.getMessage("command.join.error.maxjobs"));
	    return true;
	}
```

so something is wrong ...

**Comment by xion87** [comment]
with pex or other bukkit perms this don't happen...

**Comment by weaondara** [comment]
dafuq

**Comment by weaondara** [comment]
atm i have absolutely no clue ...

**Comment by xion87** [comment]
i pinged the author maybe he tell to you what to do

**Comment by xion87** [comment]
@Zrips

**Comment by xion87** [comment]
btw the perm work like this here
1° look the config the limit
2. if player got not permission it must get the config limit
3. if player got the permisionj obs.max.XX ignore the config and apply permission one

**Comment by weaondara** [comment]
ok ...found the error
https://github.com/Zrips/Jobs/blob/master/com/gamingmesh/jobs/PlayerManager.java#L539

**Comment by weaondara** [comment]
made issue @ https://github.com/Zrips/Jobs/issues/9

**Comment by weaondara** [comment]
jobs is fixed

**Comment by xion87** [comment]
yep working great now
