### ISSUE TITLE
Bukkit permissions with spigot not working.

### ISSUE THREAD

**Issue by SIM0NSTR** [weaondara/BungeePerms#189]

**Comment by jimmikaelkael** [comment]
Hmmm... I may be a bit short as a description.
Please be a bit more verbose if you want help.

**Comment by weaondara** [comment]
jep, just saying it doesn't work does not help anyone
post any exceptions you encounter releated to bungeeperms if any
post configs (without your mysql login data ... or any bad guy will hack your server)
post your server setup (how many mc servers)
post what's ever relavant
