### ISSUE TITLE
Exceptions on player join (bungee)

### ISSUE THREAD

**Issue by jimmikaelkael** [weaondara/BungeePerms#190]
I use the latest dev build from jenkins, mysql2 backend, using uuids, and I have exceptions when players join on the proxy:
http://pastie.org/10634717

I have another type of exceptions, but they are not related to player join
http://pastie.org/10634744

The exceptions are gone if I set saveAllUsers to true in the config. However I prefer to prevent default group users to be saved so I'll be glad if you can fix this.

**Comment by weaondara** [comment]
just fixed ... new build on the way

**Comment by jimmikaelkael** [comment]
@weaondara Tried build 26 from jenkins. Your fix doesn't solves exceptions...
pastie.org/10635460
