### ISSUE TITLE
How to use a command by the server and not by the bungeecord ?

### ISSUE THREAD

**Issue by LandrioProd** [weaondara/BungeePerms#195]
The title explains it all, I'd like to know how to run a command "/ gf .." by the server console and not by that of bungeecord.
Thanks you in advance, Landrio.

**Comment by weaondara** [comment]
use the server console?

**Comment by LandrioProd** [comment]
Yes exactly

**Comment by weaondara** [comment]
sry i don't really get what you mean

**Comment by LandrioProd** [comment]
When I want to run a command of "BungeePerms" I use the console of Bungeecord but my question is why I can't do it from the console of my different servers.

**Comment by weaondara** [comment]
you need to install bp on your servers and execute the commands there

**Comment by LandrioProd** [comment]
The command "/ bp" not yet display anything in the console.

**Comment by LandrioProd** [comment]
My BungeePerms is set on global.

**Comment by weaondara** [comment]
which version are you running?

**Comment by LandrioProd** [comment]
The last alpha version

**Comment by weaondara** [comment]
try using a dev build

**Comment by LandrioProd** [comment]
It's work
