### ISSUE TITLE
Player cant do things he has permission for

### ISSUE THREAD

**Issue by Rustypredator** [weaondara/BungeePerms#197]
If i add a permission to a group, it is displayed in the list command of the group and also of the player if he is in this group.
For example:
```
/bp group member add essentials.tpa

Added Permissions essentials.tpa to group member
```
```
>bp group member list
23:15:56 [INFORMATION] Permissions of the group member:
23:15:56 [INFORMATION] - bungeecord.command.server (own)
23:15:56 [INFORMATION] - bungeeportals.portal.* (own)
23:15:56 [INFORMATION] - -bukkit.command.plugins (own)
23:15:56 [INFORMATION] - essentials.tpaccept (own)
23:15:56 [INFORMATION] - essentials.tpdeny (own)
23:15:56 [INFORMATION] - essentials.home (member)
23:15:56 [INFORMATION] - essentials.sethome (member)
23:15:56 [INFORMATION] - essentials.tpa (member)
23:15:56 [INFORMATION] - essentials.tpahere (member)
```
```
>bp user Rustypredator list
23:16:50 [INFORMATION] Permissions of the player Rustypredator:
23:16:50 [INFORMATION] - bungeecord.command.server (newbie)
23:16:50 [INFORMATION] - bungeeportals.portal.* (newbie)
23:16:50 [INFORMATION] - -bukkit.command.plugins (newbie)
23:16:50 [INFORMATION] - essentials.tpaccept (newbie)
23:16:50 [INFORMATION] - essentials.tpdeny (newbie)
23:16:50 [INFORMATION] - essentials.home (member)
23:16:50 [INFORMATION] - essentials.sethome (member)
23:16:50 [INFORMATION] - essentials.tpa (member)
23:16:50 [INFORMATION] - essentials.tpahere (member)
```
But i still can not /tpa <player>

**Comment by weaondara** [comment]
have you linked the servers to the same mysql db?
is the backend mysql2 and the uuidplayerdb mysql?
try executing the same commands on the spigot console

**Comment by Rustypredator** [comment]
Hi,
Those commands were done from the bunggecord console, and if i run these on one of the servers the output is the same. The config is correct, and i dont have any connectivity problems to the database.

**Comment by weaondara** [comment]
hi you can enable the debug mode on the spigot and see which perms are checked and what the results are
maybe this helps you

**Comment by Rustypredator** [comment]
you mean to enable the debug mode of bungeeperms?

**Comment by Rustypredator** [comment]
Ok, it seems to work now, but i need to reload / restart the server every time i make changes to the permissions, because it has no effect otherwise...

**Comment by Rustypredator** [comment]
so... the database connection seems to be the problem. it works sometimes, and sometimes it does not. i dont know what causes the issue, but i dont think it is your plugin :) thanks for your time.
