### ISSUE TITLE
Prefix Reset not working

### ISSUE THREAD

**Issue by NullPatrol** [weaondara/BungeePerms#205]
terminate.prefix.reset does not seem to work.
Version 3.0 alpha-1 installed on a spigot & bungee server. Both with the same terminate attributes.
Issue seems to lie with the spigot instance.

I want to have a color after the prefix for all users: "&7[&5Admin&7] &d"
But the &d doesn't seem to go through. if I use "&7[&5Admin&7]&d" with space to true, it doesn't add the space either.

tabcomplete: true
locale: en-GB
servername: Hub
terminate:
  prefix:
    reset: false
    space: false
  suffix:
    reset: false
    space: false
allowops: false
superpermscompat: false

**Comment by weaondara** [comment]
did you use a dev-build?
if not please get the latest version at http://ci.wea-ondara.net/job/BungeePerms/
and check if the problem persists, thx

**Comment by NullPatrol** [comment]
The problem ceased to exist after using a dev build
