### ISSUE TITLE
How to setup spigot plugin

### ISSUE THREAD

**Issue by Paktosan** [weaondara/BungeePerms#207]
So if I unterstood what this plugin is capable to do I should be able to connect my spigot server to the same database my bungee is connected to so they use the same permission set, right? However I am unable to connect my spigot to the database. The section in the config is missing and copying the section of the bungee doesn´t work. What is the proper way to do it? I am using build 33 currently.

**Comment by weaondara** [comment]
maybe you corrupted your yaml config (tabs and spaces mixed up, or sth like that)
the config section of myswl is the same
and yeah it should be the same db

**Comment by Paktosan** [comment]
Ok, I found the issue. There were too many spaces. Thanks!
