### ISSUE TITLE
Plugin reloads itself infinitely

### ISSUE THREAD

**Issue by LazoCreations** [weaondara/BungeePerms#208]
I have a bungeecord and a spigot server. I put Bungeeperms plugin each of them
and set backend option as MySQL2. After I completed the setup,
everything seem to work fine except one thing..
When a player types /bp reload, server doesn't do it properly.
It reloads the plugin infinitely so I had to shut down the server.

![default](https://cloud.githubusercontent.com/assets/9482578/12215111/a999936c-b6f1-11e5-9255-f01fc9b4655f.JPG)

Log files: 
[debug.txt](https://github.com/weaondara/BungeePerms/files/83577/debug.txt)
[latest.txt](https://github.com/weaondara/BungeePerms/files/83578/latest.txt)
[bungee bp-config.txt](https://github.com/weaondara/BungeePerms/files/83580/bungee.bp-config.txt)
[spigot bp-config.txt](https://github.com/weaondara/BungeePerms/files/83581/spigot.bp-config.txt)

I'm using the latest version (3.0-alpha-1) of BungeePerms and latest version of Spigot, bungeecord.

**Comment by weaondara** [comment]
please try a dev build from ci.wea-ondara.net
that should fix that problem
