### ISSUE TITLE
Error with Ontime plugin

### ISSUE THREAD

**Issue by Desertive** [weaondara/BungeePerms#21]
I have fully explained the problem at Ontime's ticketing system: http://dev.bukkit.org/bukkit-plugins/ontime/tickets/398-problem-with-bungee-perms/

So basically I'm not sure if this problem lies in Ontime or your dev-build Vault, but something there is that doesn't let Ontime to change players' ranks. I think you can say faster where the problem lies.

Thank you!

**Comment by weaondara** [comment]
in bp 3.0
