### ISSUE TITLE
" OP " is broken

### ISSUE THREAD

**Issue by LandrioProd** [weaondara/BungeePerms#210]
Hello,
Recent plugin updates of BungeePerms breaks the usage of "OP".
Just to inform you, thanks in advance.

**Comment by xion87** [comment]
https://github.com/weaondara/BungeePerms/issues/103

**Comment by MCTyler** [comment]
Perm is minecraft.command.op, It works!

**Comment by LandrioProd** [comment]
I don't speak of the command " /OP ".

**Comment by weaondara** [comment]
enable allowops in your config and it should work

**Comment by MCTyler** [comment]
So What is OP besides the Command /Op? I'm confused????

**Comment by MCTyler** [comment]
Are you talking about the built in Perms of the plugin(s) that are designated for OP?

**Comment by LandrioProd** [comment]
Since the plugin update, being "Op" is meaningless and gives no permissions.

**Comment by MCTyler** [comment]
Like @weaondara said, Enable allowops and superperms in the config and it works fine. Not really sure why this is even a setting though, It just causes confusion.

**Comment by xion87** [comment]
enable:
allowops: true
superpermscompat: true

Some plugin that require OP dont work and it just say no permission!

**Comment by MCTyler** [comment]
I noticed that with ChestCommands that has the option to allow Menu Items to run commands as Ops. Must be some kind of Vault hook or something. My Work around was rather cumbersome, I gave the permission to run the command but used a command blocker (CDNE) to not allow direct running of the command from the command line since I charge a fee to run the command.

**Comment by weaondara** [comment]
> Are you talking about the built in Perms of the plugin(s) that are designated for OP?
yes, if allowops is true op get their op default perms
if disabled they are not granted the op default perms

**Comment by xion87** [comment]
I have allowops  enabled
i can use op comman and all, but some plugin stopped to recognize the op,(example i get muted for spam, i cant use essentials commands, ecc)

**Comment by weaondara** [comment]
please execute /bp user <you> has <permission> on the spigot console to test and send me a list of ess commands that don't work

**Comment by xion87** [comment]
try to install essentialsX, and have lastest bungeeperms jenskin, you can't any execute any command like thor, kit, teleport, warp

**Comment by xion87** [comment]
also all multiverse commands, ecc...

**Comment by MCTyler** [comment]
...Agree In my opinion, If your Op, you should have all the perms, in all the worlds, just like Pex.

**Comment by xion87** [comment]
@MCTyler i suggested this because of bukit config op-level....

**Comment by weaondara** [comment]
@xion87 jep
@MCTyler you can add * if you want to have all perms

**Comment by xion87** [comment]
so i just have to add * permission?

**Comment by weaondara** [comment]
* will grant you all perms

**Comment by xion87** [comment]
so here "op" mean nothing... xD

**Comment by weaondara** [comment]
if you don't want to have certain perms just remove them afterwards

**Comment by sgdc3** [comment]
So... how bungeeperms does manage op players?

**Comment by LandrioProd** [comment]
So add the " '*' " permissions will give all permissions like Op.

**Comment by sgdc3** [comment]
Yeah but why there is an allowOp feature?

**Comment by sgdc3** [comment]
@weaondara

**Comment by weaondara** [comment]
if allowops=true then bungeeperms doues not alter the op-permissions behavior
if false then ops only have default perms as any other player
it's only relevant if superpermscompat is true

**Comment by xion87** [comment]
so is normal that if i have
allowops: true
superpermscompat: true

permission dont work also i am op?

**Comment by weaondara** [comment]
if the perm is not op-default or true-default then yes

**Comment by weaondara** [comment]
which perms don't work in your opinion?

**Comment by xion87** [comment]
i told you, the essentials one, multiverse ones, must be added manually/or use *

**Comment by weaondara** [comment]
as far as i can see mv does not have any default perms

**Comment by xion87** [comment]
ok, ty the clarification i will use "*" and negate the permission that i dont want for my admin :) as you said
