### ISSUE TITLE
Backend migration error

### ISSUE THREAD

**Issue by LazoCreations** [weaondara/BungeePerms#213]
14.01 03:50:10 [Server] INFO Finished migration.
14.01 03:50:10 [Server] SEVERE at java.lang.Thread.run(Unknown Source)
14.01 03:50:10 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
14.01 03:50:10 [Server] SEVERE at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
14.01 03:50:10 [Server] SEVERE at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin$1$1.run(BungeePlugin.java:100)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onCommand(BungeePlugin.java:84)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.CommandHandler.onCommand(CommandHandler.java:86)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.CommandHandler.handleMigrate(CommandHandler.java:2010)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.CommandHandler.handleMigrateBackend(CommandHandler.java:2063)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.PermissionsManager.migrateBackEnd(PermissionsManager.java:1537)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.io.migrate.Migrate2YAML.migrate(Migrate2YAML.java:35)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.io.YAMLBackEnd.saveVersion(YAMLBackEnd.java:250)
14.01 03:50:10 [Server] SEVERE at net.alpenblock.bungeeperms.Config.save(Config.java:59)
14.01 03:50:10 [Server] SEVERE java.lang.IllegalStateException: config failed to load; save not allowed
14.01 03:50:10 [Server] INFO Migrating permissions to YAML ...

**Comment by weaondara** [comment]
fixed in dev-build 36 http://ci.wea-ondara.net/job/BungeePerms/36/
