### ISSUE TITLE
Prefix Wont Work!!

### ISSUE THREAD

**Issue by XThunderTNTX** [weaondara/BungeePerms#214]
Hi,

Im running BungeePerms V: 3.0
I set me as a admin and set a prefix..
The prefix wont showup!!! I enabled Prefixes and Suffixs in the essentials config Still not working
Please help

**Comment by weaondara** [comment]
do you use dev-builds? if not consider doing so
dev builds are available at http://ci.wea-ondara.net/job/BungeePerms/
