### ISSUE TITLE
Prefixes still not working / console errors / suggestion. (Dev build)

### ISSUE THREAD

**Issue by Deltorien** [weaondara/BungeePerms#215]
Okay so i decided to use your plugin over group manager after i tried multiple attempts at using symlinks but group manager decided to be.... group manager. so i went looking for a new plugin to fix my woes.. and i found yours... if it was not for some problems i'm having with it i would be using it.

it chucked some errors in console that i have for you, and prefixes did NOT seem to work, at all.

Okay i copied like all of bungees console juts to show you.
http://pastebin.com/iN1jfsxz

wen i ran in game commands like adding users to a group or reloading the plugin it chucked errors....
and of cause no prefix..

also for my suggestion.
If you would be so kind after you fixed these errors to allow users to customize what commands they needed to use for example /bp user NAME addgroup GROUP to for example someone could change it to

/bun u NAME ag Group

or even allow users to do more advanced things like changing the structure 

/bunuaddg NAME GROUP

/bungaddg GROUP

/bungdelg GROUP

Thanks for reading i hope you fix these glitches :)

**Comment by weaondara** [comment]
ok, i think you didn't set it up properly ....
whats your server setup? bungeecord? how many spigot servers? mysql server running?
