### ISSUE TITLE
Bukkit BungeePerms not working with UUIDs

### ISSUE THREAD

**Issue by TheRPunkt** [weaondara/BungeePerms#218]
Hey!
First of all: amazing Plugin :D But that's not what I want to say here. 

I am working on a Plugin for a spigot server which have to look up if a specific user has a permission. 

Configuration:

Bungeecord/Proxy:
- backendtype: MySQL2
- uuidplayerdb: MySQL
- useUUIDs: true

Bukkit/Spigot:
- backendtype: MySQL2

Sooo I went to the server and I was at the database. But if I looked into the Bukkit/Spigot console there was an error that it can't find me. So I tried many things. Cleaning up database,... Finally I turned of useUUIDs. And it worked. So my problem is: I have to use UUIDs but it will not work.. Hope you can fix this :/

TheRPunkt

PS: Sorry for my English :c

**Comment by weaondara** [comment]
you need to set 
```uuidplayerdb: MySQL
useUUIDs: true```
as well on spigot
furthermore check if the uuids match when a player logs in in both consoles

**Comment by TheRPunkt** [comment]
Thank you very much. It works fine for me now :3 Maybe you should add this as autogenerated line in the configs, because I had to add these lines manually :D

**Comment by weaondara** [comment]
that should already be auto generated
