### ISSUE TITLE
Bungeeperms and Worldguard regions with Jobs Reborn

### ISSUE THREAD

**Issue by Ex0rz1st2** [weaondara/BungeePerms#220]
Problem: Member of a Job-Group cant enter area. No problem with Pex.
I'm using Bungeeperms and Job-Reborn.
For being a certain Joblvl, the Jobs-plugin should give a Player a special permission. The affected players had this special permissions for being the joblvl before chancing my permission system form PEX to Bungeeperms.
 I create a region with Worldguard and for example add The group Miner10 to the members, but this is not working like it should do, no one can enter this area. It seems like Bungeeperms blocks this Group or something like this. 
Hope you can help me or find the Error...

**Comment by weaondara** [comment]
did you check if the player has the permission? (bp user <user> has <permission>)
if so enable the debug mde (bp debug true) and watch the console what the perm check results are

**Comment by Ex0rz1st2** [comment]
After playing around with the config of Bungeeperms I found out, that the solution of my problem was changing "superpermscompat" from false to true.
Thank you for the Help.
