### ISSUE TITLE
Bungeeperms prefix

### ISSUE THREAD

**Issue by Koenvuurens** [weaondara/BungeePerms#221]
Hello,

I used PermissionsEx on my 12 servers and switched over to Bungeeperms. I have Bungeeperms also connected to my MySQL server.  But when I have a prefix, wich ends on a color (&4) my name ends up white. With PermissionsEx I didn't had that problem. Chat handling is done with Legendchat because its sort of globalchat. Works like a charm, but with your plugin my name is white. Maybe its just me or you have something I can do.

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/17090293/12859533/038e108a-cc57-11e5-9d74-cec017351af1.png)

![image](https://cloud.githubusercontent.com/assets/17090293/12859466/9d3a8c1e-cc56-11e5-84d7-e0b5f8cbc476.png)

**Comment by xaoseric** [comment]
This is due to the way that the prefixes are displayed, there should be a space between the username and the display name as well. I'll release a fix in the next few days, going to fork to fix the plugin.

**Comment by Koenvuurens** [comment]
ok, because my server depends atm on it and I cant release it to the public because of this.

**Comment by weaondara** [comment]
the is a config option called terminate.prefix.reset ... set it to false and it should work 
of course on all server/bungeccord where the chat plugin is installed

**Comment by Koenvuurens** [comment]
Yes I already tried that and didn't work.

**Comment by weaondara** [comment]
ok i tested it and it's not a bp fault, it works as expected

**Comment by Koenvuurens** [comment]
Did you use a dev build or the Alpha 3.0 version?

**Comment by weaondara** [comment]
latest dev ... always

**Comment by Koenvuurens** [comment]
Ah I used the alpha version maybe it was that...?

**Comment by weaondara** [comment]
jep most likely
so did this resolve your issue? if so please close

**Comment by Koenvuurens** [comment]
I am going to test it now. I am keeping you updated

**Comment by phil568622** [comment]
Last answer was 19 Days ago, I believe Its fixed. Close Please
