### ISSUE TITLE
BungeePerms not multiServer?

### ISSUE THREAD

**Issue by AceWolf2** [weaondara/BungeePerms#222]
I went from BungeePermsBukkit to just using bungeeperms and everything went ok switched it to mysql2 and I'm only seeing groups on the bungee side not the other servers. nor can I use my permissions on any servers. is it an error on my part?

**Comment by weaondara** [comment]
check the bp config on every server where bp is installed ... check if the backend option match in every config

**Comment by AceWolf2** [comment]
ok I got it working. Now I seem to be able to get most of my permissions working. I just cannot seem to get bukkit or essentials permissions to work for some reason

**Comment by weaondara** [comment]
you can use '/bp debug true' on your spigot console and see which permisions are checked when you e.g. execute a command ... maybe you have typo
