### ISSUE TITLE
Issue with OP and World edit

### ISSUE THREAD

**Issue by punnydoge** [weaondara/BungeePerms#229]
When in allow ops false is on, world edit perms are still allowed such as //wand, cut, paste etc.

**Comment by weaondara** [comment]
we has no-op-permission option; set it to false and it should work

**Comment by punnydoge** [comment]
Weaondara, I know you get many questions from noobs, but I am very familiar with allowops: false. I have been running bungee perms in full production on a bungee network of 5 servers for about 3 months now. 

When I tell you that my config has allowops: false, and when I /op a player, they can use worldedit, I am quite serious and certain. I did /bp debug true from console and checked perms as well, just to be certain. Perhaps you could humor me and try to recreate it? I would really appreciate it, sir.
