### ISSUE TITLE
Effective group by ladder

### ISSUE THREAD

**Issue by sebastianbinder** [weaondara/BungeePerms#234]
Hi there. Is there any chance to get a user's effective group by ladder? I thought the method ``getGroupByLadder("default")`` will give me the group with the highest rank (= lowest rank count) in this ladder, but it seems that it doesn't. Any information for me about this? Because my current code doesn't look really nice - actually I only want the prefix and suffix of the group with the highest rank….
```java
Group groupToReturn = null;
for (Group group : user.getGroups()) {
  if (groupToReturn == null && group.getLadder().equalsIgnoreCase("default")) {
    groupToReturn = group;
  } else {
    if (group.getLadder().equalsIgnoreCase("default") && (group.getRank() < groupToReturn.getRank())) {
      groupToReturn = group;
    }
  }
}
return groupToReturn.getPrefix();
```

**Comment by weaondara** [comment]
it will give you some group in the ladder the user has
unfortunally it would make sense that the group with the lowest rank property is returned
reguarding your question: all groups the user has have effects but it's not recommended to have multiple groups in the same ladder on a single user
however `getMainGroup(User player)` in the permissions manager is the function your are searching for
