### ISSUE TITLE
1.9 BungeePermsBukkit

### ISSUE THREAD

**Issue by sidboy55555** [weaondara/BungeePerms#235]
Hi, I would love to that BungeePermsBukkit would be updated to 1.9 quick, not that i'm puching you now but just if you did't notice that spigot 1.9 is released :P , http://pastebin.com/H7wCys23 this is the error if you want to see it :)

**Comment by weaondara** [comment]
do you really mean the BungeePermsBukkit.jar?

**Comment by sidboy55555** [comment]
yeay, the BungeePerms.jar is working in the latest bungeecord that supports 1.9, but the BungeePermsBukkit.jar is not working with the 1.9 spigot version.

**Comment by weaondara** [comment]
the BungeePerms.jar is for both bungee and spigot since bp 3.0

**Comment by sidboy55555** [comment]
yes, but i want the BungeePermsBukkit.jar for prefixes, I did´t find any good bungee plugin for prefixes so i use my old one simple prefix, that the BungeePermsBukkit.jar wil be connected with vault and then simple prefix can read it.

**Comment by sidboy55555** [comment]
okay thnx

**Comment by weaondara** [comment]
is this issue done?
 if so please close
