### ISSUE TITLE
Prefix bug

### ISSUE THREAD

**Issue by logtainment** [weaondara/BungeePerms#242]
Hey,
I have a Bug
If I set the Prefix to &cAdmin.
The Chat displays Admin null Name

**Comment by xXTsunami72Xx** [comment]
I have the same problem prefix null and suffix null, 
I happens when the option is activated saveAllUsers: true, and /bp user USERNAME add PERMISSION
the bug occurs "null".

**Comment by weaondara** [comment]
i receommend to use the mysql2 backend which has a much better db layout and is not deprecated
