### ISSUE TITLE
useUUIDs is broken

### ISSUE THREAD

**Issue by skillerfox3** [weaondara/BungeePerms#243]
Hello there,

I have got 2 servers, a bungee server and a lobby server. When I enable the _useUUIDs_ in the lobby AND in the bungee server I get the following error misconfiguration: "_[BungeePerms] ?4Misconfiguration: UUIDs on Bungeecord and Bukkit/Spigot differ. Check your Spigot/Bukkit and Bungeecord config!_". I have tried this on a just set-up server, no sql tables, permissions and users before I changed the config. No errors, no issues with sql.

Permissions don't work with this enabled. And as I want people to change their names this configuration must be toggled to true!

I would love a fix!

Kind regards,
skillerfox3

Spigot config:

```
useUUIDs: true
useregexperms: false
grouppermission: true
backendtype: MYSQL2
uuidplayerdb: MYSQL
tablePrefix: bungeeperms_
uuidfetcher:
  cooldown: 3000
saveAllUsers: true
deleteUsersOnCleanup: false
notify:
  promote: false
  demote: false
tabcomplete: false
locale: en-GB
terminate:
  prefix:
    reset: true
    space: true
  suffix:
    reset: true
    space: true
cleanup:
  interval: 1800
  threshold: 600
async-commands: true
servername: lobby
allowops: true
superpermscompat: false
standalone: false
debug:
  path: /home/minecraft/Lobby/plugins/BungeePerms/logs/debug.log
  showexceptions: true
  showlogs: false
bungeeperms:
  general:
    mysqlhost: ****
    mysqlport: '****'
    mysqldb: ****
    mysqluser: ****
    mysqlpw: ****
```

Bungee config:

```
useUUIDs: true
useregexperms: false
grouppermission: true
backendtype: MYSQL2
uuidplayerdb: MYSQL
tablePrefix: bungeeperms_
uuidfetcher:
  cooldown: 3000
saveAllUsers: true
deleteUsersOnCleanup: false
notify:
  promote: false
  demote: false
tabcomplete: false
locale: en-GB
terminate:
  prefix:
    reset: true
    space: true
  suffix:
    reset: true
    space: true
cleanup:
  interval: 1800
  threshold: 600
async-commands: true
networktype: Global
networkservers: []
debug:
  path: /home/minecraft/Bungee/plugins/BungeePerms/logs/debug.log
  showexceptions: true
  showlogs: false
bungeeperms:
  general:
    mysqlhost: ****
    mysqlport: '****'
    mysqldb: ****
    mysqluser: ****
    mysqlpw: ****
```

**Comment by weaondara** [comment]
you forgot to configure the spigot server correctly .. maybe the bungeecord is set to false in the spigot server config

**Comment by skillerfox3** [comment]
I did set IP forwarding to false in the bungee config and Bungeecord to false in the Spigot config. Its configured how I want it to be. This should not have to break the BungeePerms plugin.

**Comment by weaondara** [comment]
well than you cant use uuids for authentication in bp
it's require that the uuids match on bungee and spigot when useuuids is set to true

**Comment by i9hdkill** [comment]
If you set bungeecord to false in spigot and your user changes the username, he will lose everything. Ranks/permissions, inventory, stuff from every plugin that uses uuids or names.
You can use a converter to convert your existing offline-mode inventories to online-mode inventories (bungeecord: true)
You can use it that way, but everytime a user changes his name, you need to give him all the stuff back manually. Might work on a server with 10 players, but not when you are expecting more players.
