### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tryolivier** [weaondara/BungeePerms#244]
Hello =)

 have this error http://pastebin.com/aKKzs1HE

 You know what is the problem ? 

thanks

**Comment by weaondara** [comment]
did you actually read what btlp said?
> An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.

**Comment by tryolivier** [comment]
I read that but I have configured it worked good before in 1.8


Thanks


Envoyé via Outlook Mobile



De : weaondara

Envoyé : jeudi 17 mars 18:16

Objet : Re: [BungeePerms] bug (#244)

À : weaondara/BungeePerms

Cc : tryolivier



did you actually read what btlp said?


An error occurred while querying data from BungeePerms. Make sure you have configured BungeePerms to use it's uuidPlayerDB.

**Comment by i9hdkill** [comment]
Make sure you are on the latest btlp build and at least the bungeeperms build provided on the spigot page. Does the uuid database actually work? This setup works fine for me, so I assume there is a mistake in your setup.

**Comment by tryolivier** [comment]
I have the last bungeecord last build and last bungeeperms


Envoyé via Outlook Mobile






On Sat, Mar 19, 2016 at 2:40 PM -0700, "John" <notifications@github.com> wrote:





Make sure you are on the latest btlp build and at least the bungeeperms build provided on the spigot page. Does the uuid database actually work? This setup works fine for me, so I assume there is a mistake in your setup.

---

**Comment by weaondara** [comment]
please try the latest dev build from ci.wea-ondara.net

**Comment by tryolivier** [comment]
all works with the last build

thanks ;)
