### ISSUE TITLE
Listing all users in a specific group don't work

### ISSUE THREAD

**Issue by fabien91** [weaondara/BungeePerms#246]
Hi,

I've lastest version of BungeeCord (1.8-1.9) and last version of BungeePerms
The command for listing users in a group don't work. (/bungeeperms group [group] users)
No error in game.
But i've this in console : http://pastebin.com/Nb2UPkZb
Can you fix this please ?

Sincerely,
Fabien

**Comment by weaondara** [comment]
please use the mysql2 backend ... mysql is deprecated

**Comment by fabien91** [comment]
What is mysql2 ?
I use the last version of mysql (5.5) on my dedcated server with many database

**Comment by weaondara** [comment]
it's just another backend which still uses mysql
