### ISSUE TITLE
Essentials issue [Fixed]

### ISSUE THREAD

**Issue by Joe26** [weaondara/BungeePerms#247]
Hi, When I had pex and essentials when i joined the server it came up with my group and name and the motd when I joined now when I use bungeeperms it doesn't its a slight bug that annoys me and is a very slight downfall to me using this, is there any fix for it or are you planning on making a fix?

**Comment by weaondara** [comment]
which essentials feature is that?

**Comment by Joe26** [comment]
Motd

**Comment by Joe26** [comment]
Sorry just me being very very stupid and typed wrong permission node for essentials motd
