### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by Serializator** [weaondara/BungeePerms#248]
Please...
Improve your database design!

**Comment by weaondara** [comment]
just complaining will not improve it ... make suggestions

**Comment by Serializator** [comment]
A database isn't the same as a configuration file with a path, use separate tables/columns for data and normalize it.

**Comment by weaondara** [comment]
did you try the mysql2 bsackend? it uses mysql ... just to clearify that

**Comment by Serializator** [comment]
It's not what I'm talking about, I'm talking about your database design/structure. The only columns you have are "key" and "value" and you use paths such as (example) "groups.test.prefix" as the key and the prefix as the value.

You could split your current table/columns into (example):
    - groups
    - group_options
    - group_permissions
    - group_inheritances

**Comment by Sponges** [comment]
my s q l = relational database
use it as a relational database

**Comment by Serializator** [comment]
What's with the spacing @Sponges x-)

**Comment by Sponges** [comment]
Stop BUllyINg mE @Serializator

**Comment by aurorasmiles** [comment]
This was the old backend, which is now deprecated. Please use MySQL2 as a backend.
