### ISSUE TITLE
Display Rank is Always [default]

### ISSUE THREAD

**Issue by xPoseidon24** [weaondara/BungeePerms#251]
Hello weaondara,
I created a permissions file using only commands. I then reloaded the bungeeperms permission.yml, except my rank is [default]. So I had a friend make me a new one, so I imported the content (copy and paste) to permissions.yml. I then proceeded and reloaded the file, went on my server, typed in chat, and my rank was still default! 

I made a whole new permissions with only 1 rank (Serf) with the default set to true, and the display to &7[&fSerf&7]. I reloaded and the same thing. It is still [default]! 

Thank you for taking the time to read this! Please help me! 
- xPoseidon

**Comment by weaondara** [comment]
what chat plugin do you use? possibly '/bpbb reload' will fix it

**Comment by xPoseidon24** [comment]
I have tried SimpleBungeeChat, EssentialsChat, iChat, mChat, and SimplePrefix

**Comment by weaondara** [comment]
have you tried /vault-info and see if bungeeperms is hooked?
