### ISSUE TITLE
Prefix taken from group with highest weight

### ISSUE THREAD

**Issue by zedwick** [weaondara/BungeePerms#253]
Testing using BungeeTabListPlus, the prefix for a player is taken from the group with the highest weight, rather than the lowest.

'Weight: Determines which group is the primary group of a player. The group with the lowest value of all groups the player is in is the primary group. (default: 1000 (1500 on group creation))'
https://github.com/weaondara/BungeePerms/wiki/Groups

BungeePerms: 3.0 dev b52
BungeeTabListPlus: 2.4.4

**Comment by weaondara** [comment]
maybe i should update that ...
clarification: the weight determines whiuch group is the main group if there is more than one group with the same rank value

**Comment by aurorasmiles** [comment]
Should be fixed in the latest version
