### ISSUE TITLE
Question - parent/children permissions nodes and default permission nodes

### ISSUE THREAD

**Issue by GoadingGoat** [weaondara/BungeePerms#254]
I'm slightly confused as to how the whole bungeecord-spigot system works... i currently have bungeeperms on both spigot and bungeecord, and have separate databases for each spigot server that perform replication of the bungeecord database, and it mostly works. The only issues i run into is when trying to give parent nodes such as gesuit.teleports.user which is supposed to give the child permissions :
gesuit.teleports.command.tpahere
gesuit.teleports.command.tpa
gesuit.teleports.command.tpaccept
gesuit.teleports.command.tpdeny
but it doesn't give the child nodes...instead i have to specify each child node.

the other issue i have is that bungeeperms seems to override the permissions that bukkit plugins give by default in their plugin.yml files, why is this? Have i misconfigured something?

**Comment by weaondara** [comment]
ok,
you need to enable superpermscompat in the bungeeperms spigot configs
that should fix both problems

btw 1 database for all server (spigot + bungee) would be enought ... you can add permissions on servers or even world only

**Comment by GoadingGoat** [comment]
Awesome, thank you very much.

1 database would work if all the servers were on the same machine, but they are not. i'd probably have been able to get away with one if they were all run from the same host, but when one some of them are in Canada, and some are in New Zealand, well.... lets just say loading a database from halfway around the world just doesn't really work.

**Comment by weaondara** [comment]
yeah

**Comment by weaondara** [comment]
is this done? than close please
