### ISSUE TITLE
Wäre is the overriding code?

### ISSUE THREAD

**Issue by AnonymChaos** [weaondara/BungeePerms#258]
Were did you Override the built-in permission system from Bungee? I really want to understand it.

**Comment by weaondara** [comment]
hook the PermissionCheckEvent

**Comment by AnonymChaos** [comment]
How do i do this?

**Comment by phil568622** [comment]
If you're really wanting to make your own permissions Plugin, you should know that...
Also, this is meant for problems with BungeePerms

**Comment by AnonymChaos** [comment]
I want to make my own for private use, just because I want to connect it via WebInterface. I know how to register events, but dont know how to hook into it. Is it just a line or a bunch of code?

**Comment by phil568622** [comment]
There you go:
http://goo.gl/PeQKkP

**Comment by AnonymChaos** [comment]
An I thought it would be very hard to make.
Thank you
