### ISSUE TITLE
sql migration

### ISSUE THREAD

**Issue by SirCoolness** [weaondara/BungeePerms#259]
when i try using mysql for my permissions it will give allot of errors and not work when i use the migration command.
`
20:24:28 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@3449be22, id=2, owner=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin@38e8df29, task=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin$1$1@4d90b2ca, delay=0, period=0, running=true) encountered an exceptionjava.lang.NullPointerException    at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onCommand(BungeePlugin.java:84)    at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin$1$1.run(BungeePlugin.java:100)    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)    at java.lang.Thread.run(Thread.java:745)>`

and when i try setting it through the config during startup the startup says this.
`
20:25:27 [INFO] [BungeePerms] extracting lang/EN-gb.yml
20:25:27 [INFO] [BungeePerms] extracted lang/EN-gb.yml

20:25:31 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

20:25:31 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:25:31 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
20:25:31 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:25:31 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
20:25:31 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
20:25:31 [SEVERE]     at com.mysql.jdbc.Util.getInstance(Util.java:360)
20:25:31 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)

20:25:31 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
20:25:31 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
20:25:31 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)

20:25:31 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2144)

20:25:31 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
20:25:31 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
20:25:31 [SEVERE]     at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
20:25:31 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:25:31 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
20:25:31 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:25:31 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
20:25:31 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
20:25:31 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
20:25:31 [SEVERE]     at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)

20:25:31 [SEVERE]     at java.sql.DriverManager.getConnection(DriverManager.java:571)
20:25:31 [SEVERE]     at java.sql.DriverManager.getConnection(DriverManager.java:215)
20:25:31 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.connect(Mysql.java:40)
20:25:31 [SEVERE]     at net.alpenblock.bungeeperms.io.MySQLBackEnd.<init>(MySQLBackEnd.java:41)

20:25:31 [SEVERE]     at net.alpenblock.bungeeperms.PermissionsManager.loadConfig(PermissionsManager.java:81)

20:25:31 [SEVERE]     at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:62)
20:25:31 [SEVERE]     at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)

20:25:31 [SEVERE]     at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
20:25:31 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
20:25:31 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)

20:25:31 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:262)
20:25:31 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
20:25:31 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

20:25:31 [SEVERE] Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'bungeeperms'@'%' to database 'bungeeperms'

20:25:31 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:25:31 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
20:25:31 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

20:25:31 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
20:25:31 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
20:25:31 [SEVERE]     at com.mysql.jdbc.Util.getInstance(Util.java:360)

20:25:31 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
20:25:31 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
20:25:31 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
20:25:31 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
20:25:31 [SEVERE]     at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
20:25:31 [SEVERE]     at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
20:25:31 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234)
20:25:31 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
20:25:31 [SEVERE]     ... 23 more

20:25:35 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
20:25:35 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:25:35 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
20:25:35 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:25:35 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

20:25:35 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)

20:25:35 [SEVERE]     at com.mysql.jdbc.Util.getInstance(Util.java:360)
20:25:35 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)

20:25:35 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
20:25:35 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
20:25:35 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
20:25:35 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2144)
20:25:35 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)

20:25:35 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
20:25:35 [SEVERE]     at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
20:25:35 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:25:35 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
20:25:35 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:25:35 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)

20:25:35 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)

20:25:35 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
20:25:35 [SEVERE]     at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
20:25:35 [SEVERE]     at java.sql.DriverManager.getConnection(DriverManager.java:571)
20:25:35 [SEVERE]     at java.sql.DriverManager.getConnection(DriverManager.java:215)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.connect(Mysql.java:40)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.reconnect(Mysql.java:307)

20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.checkConnection(Mysql.java:301)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:216)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:98)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.tableExists(Mysql.java:116)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.MysqlConfig.createTable(MysqlConfig.java:69)

20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.io.MySQLBackEnd.<init>(MySQLBackEnd.java:46)

20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.PermissionsManager.loadConfig(PermissionsManager.java:81)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:62)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
20:25:35 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
20:25:35 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
20:25:35 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:262)
20:25:35 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
20:25:35 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:25:35 [SEVERE] Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'bungeeperms'@'%' to database 'bungeeperms'
20:25:35 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:25:35 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
20:25:35 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:25:35 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
20:25:35 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
20:25:35 [SEVERE]     at com.mysql.jdbc.Util.getInstance(Util.java:360)
20:25:35 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)

20:25:35 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
20:25:35 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
20:25:35 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
20:25:35 [SEVERE]     at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
20:25:35 [SEVERE]     at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)

20:25:35 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234)

20:25:35 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
20:25:35 [SEVERE]     ... 29 more
20:25:35 [SEVERE] java.lang.NullPointerException

20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:217)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.returnQuery(Mysql.java:98)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.tableExists(Mysql.java:116)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.MysqlConfig.createTable(MysqlConfig.java:69)

20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.io.MySQLBackEnd.<init>(MySQLBackEnd.java:46)

20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.PermissionsManager.loadConfig(PermissionsManager.java:81)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:62)
20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)

20:25:35 [SEVERE]     at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
20:25:35 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
20:25:35 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
20:25:35 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:262)

20:25:35 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)

20:25:35 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

20:25:39 [SEVERE] com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
20:25:39 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

20:25:39 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)

20:25:39 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:25:39 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
20:25:39 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
20:25:39 [SEVERE]     at com.mysql.jdbc.Util.getInstance(Util.java:360)
20:25:39 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)

20:25:39 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
20:25:39 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
20:25:39 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
20:25:39 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2144)
20:25:39 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
20:25:39 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)

20:25:39 [SEVERE]     at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)

20:25:39 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:25:39 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
20:25:39 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:25:39 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
20:25:39 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)

20:25:39 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)

20:25:39 [SEVERE]     at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
20:25:39 [SEVERE]     at java.sql.DriverManager.getConnection(DriverManager.java:571)
20:25:39 [SEVERE]     at java.sql.DriverManager.getConnection(DriverManager.java:215)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.connect(Mysql.java:40)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.reconnect(Mysql.java:307)

20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.checkConnection(Mysql.java:301)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.runQuery(Mysql.java:248)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.Mysql.runQuery(Mysql.java:102)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.MysqlConfig.createTable(MysqlConfig.java:76)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.io.MySQLBackEnd.<init>(MySQLBackEnd.java:46)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.PermissionsManager.loadConfig(PermissionsManager.java:81)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:62)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)
20:25:39 [SEVERE]     at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
20:25:39 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
20:25:39 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
20:25:39 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:262)
20:25:39 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)

20:25:39 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:25:39 [SEVERE] Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'bungeeperms'@'%' to database 'bungeeperms'
20:25:39 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:25:39 [SEVERE]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
20:25:39 [SEVERE]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:25:39 [SEVERE]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
20:25:39 [SEVERE]     at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)

20:25:39 [SEVERE]     at com.mysql.jdbc.Util.getInstance(Util.java:360)
20:25:39 [SEVERE]     at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
20:25:39 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
20:25:39 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
20:25:39 [SEVERE]     at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
20:25:39 [SEVERE]     at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
20:25:39 [SEVERE]     at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
20:25:39 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234)
20:25:39 [SEVERE]     at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2085)
20:25:39 [SEVERE]     ... 28 more
20:25:39 [WARNING] Error enabling plugin BungeePermsjava.lang.RuntimeException: java.lang.NullPointerException    at net.alpenblock.bungeeperms.Mysql.runQuery(Mysql.java:256)    at net.alpenblock.bungeeperms.Mysql.runQuery(Mysql.java:102)    at net.alpenblock.bungeeperms.MysqlConfig.createTable(MysqlConfig.java:76)    at net.alpenblock.bungeeperms.io.MySQLBackEnd.<init>(MySQLBackEnd.java:46)    at net.alpenblock.bungeeperms.PermissionsManager.loadConfig(PermissionsManager.java:81)    at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:62)    at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)    at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:262)    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)Caused by: java.lang.NullPointerException    at net.alpenblock.bungeeperms.Mysql.runQuery(Mysql.java:249)    ... 12 more
`

**Comment by akiva3577** [comment]
nevermind i just got the database caps wrong
for the future can the error just be access denied or somthing

**Comment by weaondara** [comment]
new issue -> #260
