### ISSUE TITLE
Problem to get group from player

### ISSUE THREAD

**Issue by Alexroge** [weaondara/BungeePerms#266]
Hello, i write you for a question ?

How i can get the group from player ?
`BungeePerms.getInstance().getPermissionsManager().getUser(p.getUniqueId()).getGroups().contains("Admin")`

or 

`BungeePerms.getInstance().getPermissionsManager().getUser(p.getUniqueId()).getGroups().equals("Admin")`

the two codes do not work

I tested this with:
`		if(BungeePerms.getInstance().getPermissionsManager().getUser(p.getUniqueId()).getGroups().contains("Admin")){
			p.sendMessage("Hello admin !");
		}else if(BungeePerms.getInstance().getPermissionsManager().getUser(p.getUniqueId()).getGroups().contains("Helper")){
			p.sendMessage("Hello Helper !");
		}`
Thanks

**Comment by fabien91** [comment]
Yes, same problem with last version of BungeeCord

Try with p.getName() ?

**Comment by Alexroge** [comment]
Thanks :)
