### ISSUE TITLE
plugin bug or javaerror? help me 

### ISSUE THREAD

**Issue by km70** [weaondara/BungeePerms#277]
18.07 19:59:26 [Server] SEVERE Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@53de625d, id=77, owner=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin@6150c3ec, task=net.alpenblock.bungeeperms.platform.bungee.BungeePlugin$1$1@2a492f2a, delay=0, period=0, running=true) encountered an exception 18.07 19:59:26 [Server] INFO java.lang.StackOverflowError 18.07 19:59:26 [Server] INFO at java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1039) 18.07 19:59:26 [Server] INFO at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1038) 18.07 19:59:26 [Server] INFO at net.alpenblock.bungeeperms.Group.getPermsWithOrigin(Group.java:329) 18.07 19:59:26 [Server] INFO at net.alpenblock.bungeeperms.Group.getPermsWithOrigin(Group.java:333)

**Comment by km70** [comment]
or tell me how is bossinble to desgroy allmost perfect plugin (i kill it without do nothing)

**Comment by CodeCrafter47** [comment]
You might have a cyclic inheritance with your groups.
