### ISSUE TITLE
#Feature - Jedis/RedisBungee Support

### ISSUE THREAD

**Issue by Lmmb74** [weaondara/BungeePerms#278]
Hello, I simply thought that it would be awesome to add redis support to this plugin. And since RedisBungee is open-source, it would be awesome to integrate them.

**Comment by sgdc3** [comment]
@Lmmb74 If i remember well it is already supported :/

**Comment by Lmmb74** [comment]
Nope, checked in the code, nor Jedis neither RedisBungee backend, just YAML, MySQL & MySQL2

**Comment by sgdc3** [comment]
? don't confuse database with plugin messaging channels
