### ISSUE TITLE
No prefix/suffix?

### ISSUE THREAD

**Issue by Feelingly** [weaondara/BungeePerms#279]
Hello there,

I am having an problem. I am not having my prefix in the chat.
Its set in the group. When I do: /bp group Owner info or /bp group Admin info
It is saying I am having an prefix, its just saying the value of the prefix. Example ADMIN.
But its: Red and bold couloured.

Hope you can help me,

**Comment by ZetoStudio** [comment]
Hello,
getting same here

**Comment by Stijnz** [comment]
BUMP

**Comment by Primordiuss** [comment]
I have the same problem, someone can help ?

**Comment by Stijnz** [comment]
Yes, I hope there is someone who can help me.

**Comment by Robpizza** [comment]
I have the problem to 👎

**Comment by Robpizza** [comment]
Use [BungeeChat](https://www.spigotmc.org/resources/bungee-chat.12592/) And enable Local-Chat works for me (y)
