### ISSUE TITLE
help with console warnings - please?

### ISSUE THREAD

**Issue by GoadingGoat** [weaondara/BungeePerms#282]
![screenshot from 2016-08-30 02 28 59](https://cloud.githubusercontent.com/assets/11308755/18054828/938f5ef6-6e59-11e6-8b95-e51f144bb268.png)

Please help with console Warnings, they don't seem to cause any problems. I'm just wondering why i'm getting them. Any help appreciated. 

Also, this is the config file
![screenshot from 2016-08-30 02 14 03](https://cloud.githubusercontent.com/assets/11308755/18054321/7d4bf386-6e57-11e6-9614-15d31ab70f34.png)

**Comment by CodeCrafter47** [comment]
BungeePerms expects the `debug.path` config option to be set to the absolute path to the log file, not just the file name (you set it to `debug.log`). For that reason it fails to create the log file in your case. Other than that it will work fine.

**Comment by GoadingGoat** [comment]
Thanykyou CodeCrafter.
