### ISSUE TITLE
Import Permissions into MySQL

### ISSUE THREAD

**Issue by mlh1100** [weaondara/BungeePerms#283]
Is there a way to import permissions from a .yml doc to the MySQL database with a command or something like this?
Because I'm not very interessed in creating and give every singel permission by a command in the BungeeCord console in which I can't tab because of my CloudSystem...
Hopefully there is a way...

mlh1100

**Comment by CodeCrafter47** [comment]
There's the [`/bungeeperms migrate` Command](https://github.com/weaondara/BungeePerms/wiki/Commands-and-Permissions#maintenance-commands).
