### ISSUE TITLE
Removing unwanted database entries, that probably should not have been allowed as commands.

### ISSUE THREAD

**Issue by GoadingGoat** [weaondara/BungeePerms#284]
Hi, I have entries in my database i wish to remove (without breaking the database).

here are the two offending entries

![bungeescrew up](https://cloud.githubusercontent.com/assets/11308755/18149655/999a2f64-7035-11e6-94a4-0752515be82c.PNG)

command used to set them was
/bp group gamer prefix set [gamer]
and
/bp group gamer prefix set &8[&7gamer&8]

when it should have been
/bp group gamer prefix &8[&7gamer&8]

Is there an in game command that would remove these entries?

**Comment by JhOnNeY** [comment]
I can't find it anywhere in the documentation.

correct usage:
/bungeeperms group <groupname> prefix <prefix> [server [world]]

What version of bungeeperms are you using?

**Comment by GoadingGoat** [comment]
version 3.0, unsure of build number. Have since figured out how to hackily remove them. But would be nice if there was a proper way to remove them when you screw up the syntax
