### ISSUE TITLE
Problems...

### ISSUE THREAD

**Issue by Haikewl** [weaondara/BungeePerms#287]
Hey, I cant change my rank to Owner. I don't have permissions to BungeePerms this is getting really annoying, help please? 

ty

**Comment by Haikewl** [comment]
permissions.yml:
groups:
  default:
    rank: 1000
    default: true
    display: '&7'
    prefix: '&7[B]'
    suffix: ''
    inheritances: []
    permissions: 
  - bungeecord.command.server
  - bungeecord.command.list
  - litebans.notify.broadcast
  - bungeeperms.user.group.set
    weight: 1000
    ladder: default
  Helper:
    rank: 800
    default: false
    display: '&2Helper &a'
    prefix: '&2Helper &a'
    suffix: ''
    inheritances:
    - default
    permissions:
    - litebans.tempmute
    - litebans.kick
    - litebans.warn
    - litebans.togglechat.bypass
    weight: 1000
    ladder: default
  Moderator:
    rank: 600
    default: false
    display: '&dModerator &5'
    prefix: '&dModerator &5'
    suffix: ''
    inheritances:
    - Helper
    - default
    permissions:
    - litebans.ban
    - litebans.tempban
    - litebans.clearchat
    - litebans.override
    - litebans.unlimited
    - litebans.unwarn
    - litebans.history
    - litebans.warnings
    - litebans.iphistory
    - litebans.checkban
    - litebans.dupeip
    - litebans.togglechat.bypass
    - litebans.notify.dupeip_join
    weight: 1000
    ladder: default
  SrMod:
    rank: 500
    default: false
    display: '&5Senior Moderator &d'
    prefix: '&5Senior Moderator &d'
    suffix: ''
    inheritances:
    - Helper
    - default
    - Moderator
    permissions:
    - litebans.togglechat
    - litebans.clearchat.bypass
    - litebans.mutechat
    - litebans.notify.broadcast
    - litebans.notify.clearchat
    - litebans.notify.silent
    - litebans.notify.mute
    weight: 1000
    ladder: default
  Admin:
    rank: 400
    default: false
    display: '&cAdmin '
    prefix: '&cAdmin '
    suffix: ''
    inheritances:
    - Helper
    - default
    - Moderator
    - SrMod
    permissions:
    - litebans.notify.banned_join
    - litebans.notify.broadcast
    - litebans.notify.clearchat
    - litebans.notify.silent
    - litebans.notify.mute
    - litebans.notify.dupeip_join
    weight: 1000
    ladder: default
  HeadAdmin:
    rank: 300
    default: false
    display: '&4Head Admin &c'
    prefix: '&4Head Admin &c'
    suffix: ''
    inheritances:
    - Helper
    - default
    - Moderator
    - SrMod
    - Admin
    permissions:
    - litebans.*
    weight: 1000
    ladder: default
  NetworkAdmin:
    rank: 150
    default: false
    display: '&a&lNetwork Admin &c'
    prefix: '&a&lNetwork Admin &c'
    suffix: ''
    inheritances:
    - Helper
    - default
    - Moderator
    - SrMod
    - Admin
    - HeadAdmin
    permissions:
    - litebans.*
    weight: 1000
    ladder: default
  StaffManager:
    rank: 50
    default: false
    display: '&9&lStaff Manager &c'
    prefix: '&9&lStaff Manager &c'
    suffix: ''
    inheritances:
    - Helper
    - default
    - Moderator
    - SrMod
    - Admin
    - HeadAdmin
    - NetworkAdmin
    permissions:
    - litebans.*
    - bungeecord.*
    - bungeeperms.*
    weight: 1000
    ladder: default
  Owner:
    rank: 1
    default: false
    display: '&a&lOwner '
    prefix: '&a&lOwner '
    suffix: ''
    inheritances:
    - Helper
    - default
    - Moderator
    - SrMod
    - Admin
    - HeadAdmin
    - NetworkAdmin
    - StaffManager
    permissions:
    - litebans.*
    - bungeecord.*
    - bungeeperms.*
    weight: 1000
    ladder: default
version: 1

**Comment by Haikewl** [comment]
config: useUUIDs: true
useregexperms: false
grouppermission: true
backendtype: YAML
uuidplayerdb: YAML
tablePrefix: bungeeperms_
uuidfetcher:
  cooldown: 3000
saveAllUsers: true
deleteUsersOnCleanup: false
notify:
  promote: false
  demote: false
tabcomplete: false
locale: en-GB
terminate:
  prefix:
    reset: true
    space: true
  suffix:
    reset: true
    space: true
cleanup:
  interval: 1800
  threshold: 600
async-commands: true
networktype: Global
networkservers: []
debug:
  path: /home/minecraft/multicraft/servers/server18585/plugins/BungeePerms/debug.log
  showexceptions: true
  showlogs: false

**Comment by CodeCrafter47** [comment]
Use the console to put yourself in the Owner group.
