### ISSUE TITLE
Error prefix and suffix!

### ISSUE THREAD

**Issue by ThomasJorde** [weaondara/BungeePerms#289]
When i write in chat, this comes up:
![skjermbilde](https://cloud.githubusercontent.com/assets/24652364/21313418/090743ca-c5f2-11e6-87eb-7e81fab26acf.PNG)

but i did not put the null there....

**Comment by SkidmarkLive** [comment]
Happens to me. Do you use MySQL? If so, you need to switch to MySQL2.

**Comment by Craftymatt2** [comment]
@FractionGaming What chat plugin do you use to make them show up?
