### ISSUE TITLE
BungeePerms doesn't load in BungeeCord

### ISSUE THREAD

**Issue by Kopf02** [weaondara/BungeePerms#293]
Informations:
Bungeecord: Newest Version
BungeePerms: v3.0

Errorlog:
20:22:00 [SEVERE] java.io.IOException: No such file or directory
20:22:00 [SEVERE] 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
20:22:00 [SEVERE] 	at java.io.File.createNewFile(File.java:1012)
20:22:00 [SEVERE] 	at net.alpenblock.bungeeperms.Debug.<init>(Debug.java:31)
20:22:00 [SEVERE] 	at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:49)
20:22:00 [SEVERE] 	at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
20:22:00 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
20:22:00 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
20:22:00 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
20:22:00 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
20:22:00 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:22:00 [INFO] [BungeePerms] extracting lang/EN-gb.yml
20:22:00 [INFO] [BungeePerms] extracted lang/EN-gb.yml
20:22:04 [SEVERE] java.io.IOException: No such file or directory
20:22:04 [SEVERE] 	at java.io.UnixFileSystem.createFileExclusively(Native Method)
20:22:04 [SEVERE] 	at java.io.File.createNewFile(File.java:1012)
20:22:04 [SEVERE] 	at net.alpenblock.bungeeperms.Debug.log(Debug.java:98)
20:22:04 [SEVERE] 	at net.alpenblock.bungeeperms.Mysql.connect(Mysql.java:44)
20:22:04 [SEVERE] 	at net.alpenblock.bungeeperms.io.MySQL2BackEnd.<init>(MySQL2BackEnd.java:44)
20:22:04 [SEVERE] 	at net.alpenblock.bungeeperms.PermissionsManager.loadConfig(PermissionsManager.java:85)
20:22:04 [SEVERE] 	at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:62)
20:22:04 [SEVERE] 	at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)
20:22:04 [SEVERE] 	at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
20:22:04 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
20:22:04 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
20:22:04 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
20:22:04 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
20:22:04 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:22:04 [WARNING] Error enabling plugin BungeePerms
java.lang.NullPointerException
	at net.alpenblock.bungeeperms.Debug.log(Debug.java:105)
	at net.alpenblock.bungeeperms.Mysql.connect(Mysql.java:44)
	at net.alpenblock.bungeeperms.io.MySQL2BackEnd.<init>(MySQL2BackEnd.java:44)
	at net.alpenblock.bungeeperms.PermissionsManager.loadConfig(PermissionsManager.java:85)
	at net.alpenblock.bungeeperms.PermissionsManager.<init>(PermissionsManager.java:62)
	at net.alpenblock.bungeeperms.BungeePerms.<init>(BungeePerms.java:56)
	at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:63)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:309)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

On Spigot all works and the config options are the same :/
I hope I will ghet help fast

**Comment by nathanfranke** [comment]
Ah yes, just close the issue so you won't have to fix it. Genius.

**Comment by aurorasmiles** [comment]
@nathanfranke This issue is literally over 3 years old and has been fixed 2 years ago. Why do you dig out 3 year old fixed issues to comment on?
