### ISSUE TITLE
Can't  download bungeeperms and bungeeberms bukkit , link not works. 

### ISSUE THREAD

**Issue by mariaBubnova** [weaondara/BungeePerms#296]
Help me please to get your plugins, I very need for my server. Your download link not working, may be exsists another way to download them. Tell me please , how can I get these plugins. I am from Russia, sorry for my bad English)

**Comment by NicoDreamzZ** [comment]
Please try the download link from Spigot: https://www.spigotmc.org/resources/bungeeperms.25/

**Comment by mariaBubnova** [comment]
thank you, but I found another solution for my server))

2017-04-11 23:46 GMT+03:00 NicoDreamzZ <notifications@github.com>:

**Comment by KnowItAllKing** [comment]
@NicoDreamzZ the download link isn't working. Do you know where else I can get it?
