### ISSUE TITLE
Lag on Bot attack

### ISSUE THREAD

**Issue by BigMrBad** [weaondara/BungeePerms#299]
I have a large network that is being attacked by some insane. The main problem is that this plugin ends up congesting with the amount of BOT that enter the server. When I take the plugin, they "enter" the lobby but the bungeecord does not fall, thus keeping the players on their servers. But when I put the plugin, the bungeecord gets overwhelmed and falls, falling all the players. What to do?

Look: https://hastebin.com/ewefowidaf.coffeescript

**Comment by Twonox** [comment]
It's because you have `saveAllUsers: true`
Set it false, and your problem will be resolved.

**Comment by BigMrBad** [comment]
Thanks o/
