### ISSUE TITLE
Prefix Don't work

### ISSUE THREAD

**Issue by ImpactOres** [weaondara/BungeePerms#303]
I did the command to put the prefixs for groups, but it doesn't come up. I chat and it is normal.

**Comment by NicoDreamzZ** [comment]
Do you have a Chat-Plugin which is compatible to BungeePerms? Without a Chat-Plugin no prefixes or suffixes will appear.

**Comment by Craftymatt2** [comment]
@NicoDreamzZ Can you recommend any bungee chat plugins that are compatible with bungee perms?

**Comment by NicoDreamzZ** [comment]
You have to install bungeeperms on the proxy an on the server, then you have to use vault as api. I have written my own chat plugin (private) so a cannot recommend other chat plugins.
