### ISSUE TITLE
Selectors do not work in Spigot 1.12-pre5

### ISSUE THREAD

**Issue by zedwick** [weaondara/BungeePerms#307]
With bungeePerms 3.0 dev build 52 installed, selectors do not work at all in Spigot 1.12-pre5

Below are some commands and their output in chat (nothing in console)
/say @s : Selector '@s' found nothing
/say @p : Selector '@p' found nothing
/say @e : Selector '@e' found nothing
/say @a : Selector '@a' found nothing
/testfor @e : 
/testfor @s : Entity '@s' cannot be found
 /testfor @p : Entity '@s' cannot be found
/testfor @a : 
 
It seems the selectors do not work in any of the commands, have also tested using /advancement grant/revoke

**Comment by xaoseric** [comment]
Hi there, I am working on rewriting bungeeperms, and will have a fix for this soon.
