### ISSUE TITLE
Per-Server permission implement?

### ISSUE THREAD

**Issue by RefractedShadow** [weaondara/BungeePerms#309]
Can you add per-server permissions in the future?
For example I want a donor be able to do /fly in plots but not in Factions. I use MySQL and I can't change this due to the way I set things up.
Thanks!

**Comment by NicoDreamzZ** [comment]
This is already implemented, just use /bp group add PERMISSON SERVERNAME, BungeePerms have to run on Bungee and Bukkit. Take care that the servername is also in the config from the bukkitserver.
