### ISSUE TITLE
Issues with the MySQL2-database

### ISSUE THREAD

**Issue by MineTim** [weaondara/BungeePerms#310]
![20170530_225948](https://cloud.githubusercontent.com/assets/26803527/26604791/c2cfddbc-458b-11e7-8990-e7fc86f7eb38.png)

Hey :),
When I start the server, there is this warning and after finishing loading, there is no group/permission (but one session before, I created some groups and some permissions (BP wrote the permissions into the mysql-database and after restarting, the mysql-database is not empty (there are the uuids with the name of the players and the ID! But BP deleted the permissions and groups...! :C )

Please help me!!!! I use BP on Minecraft 1.11.

Greetings
Minecraft_Tim

**Comment by BlackBeltPanda** [comment]
Also having this problem after updating to MySQL 7

**Comment by MineTim** [comment]
Thank you for no response and no help! Thank you. 

Greetings
MineTim.

**Comment by aurorasmiles** [comment]
> Thank you for no response and no help! Thank you.
> 
> Greetings
> MineTim.

Hey,
I closed multiple old issues today, this one was supposed to stay open, sorry for that.

**Comment by weaondara** [comment]
Hey,
this might help you 
https://stackoverflow.com/questions/36829911/how-to-resolve-order-by-clause-is-not-in-select-list-caused-mysql-5-7-with-sel

**Comment by MineTim** [comment]
It's okay. Is that error already fixed or is that on the "to-do" (I didn't tried out...)?

Greetings
MineTim

**Comment by weaondara** [comment]
We konw of that problem by we did not fix it yet. But the link I posted is a "work-around". The work around tells the server to behave like in previous versions.

**Comment by MineTim** [comment]
At this moment, I don't have a minecraft network to test that. Maybe BlackBeltPanda is able to test that.

With posting that comment from me, I want to help others with the same problem (even I do not have a minecraft server anymore).

Hopefully BlackBeltPanda is reading this...

Greetings
MineTim

**Comment by BlackBeltPanda** [comment]
Sorry, I switched to LuckPerms

**Comment by aurorasmiles** [comment]
Should be fixed
