### ISSUE TITLE
Prefix Not Working

### ISSUE THREAD

**Issue by DylanMaster4** [weaondara/BungeePerms#313]
I'm not sure why but, the prefixs are not working. Also, not sure what you mean by a bridge plugin. In my spigot plugin folder I have essentials, essentials chat, and permisionsex. In my bungee plugin folder I have BungeePerms. I do not have MySQL2 setup. I do not know if that has to be setup to do it. I alos do not know how to setup MySQL2 and connect it. 

-DylanMaster4

**Comment by NurPech** [comment]
Just remove Permissionex from your spigot server and add there BungeePerms too. Than setup a MySQL2 Database for BungeePerms. Then it would working.
