### ISSUE TITLE
Issues with MySQL and SSL

### ISSUE THREAD

**Issue by Rustypredator** [weaondara/BungeePerms#324]
Hi, i have problems connecting my nodes via MySQL over the net using SSL

Message:
```
Tue Nov 21 21:03:56 CET 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

My Setup includes 2 Servers that are not physically located near another and are subsequently not on the same local network. (MYSQL across multiple servers worked well with local networks surprisingly).
One of the Servers houses the MySQL Server with one of the nodes.
To use the same Perms on all nodes, i want to connect all servers (using bungeeperms) to this MySQL Instance.
My problem now is, that the plugin seems to need to use SSL to connect to the Database, but i have no clue to how i would specify the certificate the plugin needs to use, in order to connect.

I can connect to the MySQL server via the cmd client using SSL certificates, so i think the MySQL server seems to be configured correctly.

Any help would be appreciated!

**Comment by aurorasmiles** [comment]
Fixed in v4, you can now specify the mysql-connection string yourself, and disable ssl for example
