### ISSUE TITLE
Download Link: BungeePerms 3.0

### ISSUE THREAD

**Issue by Erdack54** [weaondara/BungeePerms#329]
Hi, waiting for the official link works here is a link on my server: [BungeePerms-3.0.jar](https://cdn.erdack54.fr/dl/plugin/minecraft/BungeePerms_v3.0-wea_ondara.jar) : [VirusTotal](https://www.virustotal.com/#/url/41345956cb4417e5566a7d134110ef5fb5140f91aee4c99b039a1f18cd610809/detection)

**Comment by Sprungente** [comment]
they should work now. I gave an update
