### ISSUE TITLE
Get an "null" erros

### ISSUE THREAD

**Issue by Spizi83** [weaondara/BungeePerms#331]
Hi ! Little worries! I have the word "null" everywhere on the name of the players example: [Administrator] null Spizinull null. It is very problematic, disturbing ... It comes from the plugin because when I have no group it is no longer displayed, and the higher the rank is the more there is the word null ..

Thank you very much if you can help me

EDIT : I understand where the problem comes from, it's in the database, some stuff like the suffix and the prefix of all new players and grades is registered as "null" so it necessarily displays null ..
How to fix this?

**Comment by NerdyBirder** [comment]
I have this same problem and can not get rid of the "null" with prefixes. I would love a solution to this problem.

**Comment by aurorasmiles** [comment]
Should be fixed by now, if not please reopen
