### ISSUE TITLE
Plugin don't work with per Server/World Permissions

### ISSUE THREAD

**Issue by Sprungente** [weaondara/BungeePerms#332]
It saves right in the MYSQL Database but players don't have the Permission in the World/Server. It looks like Bungeeperms not recognize it

Tested on 1.13.2 with Spigot on a Bungeecordnetwork with build 1359

**Comment by aurorasmiles** [comment]
Is the servername set correctly in the bungeeperms-config on your spigot-server?

Works as intended on our testing/live server

**Comment by aurorasmiles** [comment]
not enough info provided
