### ISSUE TITLE
Group mananger plugin not working not sure if i just dont understand how to use the plugins with bungee

### ISSUE THREAD

**Issue by EvadeMc** [weaondara/BungeePerms#336]
Group manager plugin not working not sure if i just don't understand how to use the plugins with bungee
i had all kinds of  plugins like the bungee essentials and the group manager plugin thats supposed to be compatible with the bungee but its not working 

FTP Home: https://gyazo.com/ce207de0252d58830c1b48168302853f
Plugins: https://gyazo.com/94385ec4b992113bdd103286110f173f

Hub Ftp: https://gyazo.com/36fc91a8e9a0be5445118d9f711283f7
Hub plugins: https://gyazo.com/55ce26511ecc2a3baec512de29335ada

Server Chat: https://gyazo.com/878b8777f43df3bb48cf5f77f8e8721b

https://gyazo.com/7b3c2a200ad1e76f8da0ba9f7770b5aa

HELP ME OUT!

**Comment by aurorasmiles** [comment]
Hi,
we can only help you if you provide more information. Please provide a log from your server and a description of your problem.
It seems like you are using multiple permission managers like LuckPerms, GroupManager and BungeePerms.
Please take a look in our wiki, you can find helpful stuff there.

**Comment by aurorasmiles** [comment]
Not enough information
