### ISSUE TITLE
it will not save on mysql

### ISSUE THREAD

**Issue by basboy1743** [weaondara/BungeePerms#338]
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.config.YamlConfiguration.loadFromString(YamlConfiguration.java:46)
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.config.FileConfiguration.load(FileConfiguration.java:61)
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.config.FileConfiguration.load(FileConfiguration.java:41)
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.config.FileConfiguration.load(FileConfiguration.java:66)
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.Config.load(Config.java:35)
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.Config.getEnumValue(Config.java:155)
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.BPConfig.load(BPConfig.java:65)
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.platform.bungee.BungeeConfig.load(BungeeConfig.java:25)
14:58:59 [SEVERE] at net.alpenblock.bungeeperms.platform.bungee.BungeePlugin.onLoad(BungeePlugin.java:53)
14:58:59 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:329)
14:58:59 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:232)
14:58:59 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:266)
14:58:59 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
14:58:59 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
14:58:59 [SEVERE] Caused by: mapping values are not allowed here

**Comment by aurorasmiles** [comment]
Please provide more information on:
- What did you try to do
- The WHOLE exception, not just half of it

**Comment by basboy1743** [comment]
I fixed it I was given the wrong port number

**Comment by basboy1743** [comment]
wanes I migrate the backend file to mysql2 no groups are found
