### ISSUE TITLE
Is there a Discord/forum/chat we can contact and discuss stuff with you?

### ISSUE THREAD

**Issue by theresajayne** [weaondara/BungeePerms#342]
@weaondara Is there a discord we can chat on, I am trying to understand how this all works with bungee, but also am a pro Java dev with Agile/Devops background in Java C# and C++

**Comment by theresajayne** [comment]
Also pulled the latest and am unable to compile as its showing errors on the bungeecord api stuff, 
Downloaded: http://nexus.theyeticave.net/content/repositories/pub_releases/net/md-5/bungeecord-chat/1.12-SNAPSHOT/maven-metadata.xml (2 KB at 9.3 KB/sec)
[WARNING] The metadata C:\Users\TheresaJayne\.m2\repository\net\md-5\bungeecord-chat\1.12-SNAPSHOT\maven-metadata-vault-repo.xml is invalid: entity reference name can not contain character =' (position: START_TAG seen ...com/main?ParticipantID=mg76cjr54t8kx45jjw4j4k9j5hsr5m26&FailedURI=... @1:270) 
[WARNING] The metadata C:\Users\TheresaJayne\.m2\repository\net\md-5\bungeecord-chat\1.12-SNAPSHOT\maven-metadata-vault-repo.xml is invalid: entity reference name can not contain character =' (position: START_TAG seen ...com/main?ParticipantID=mg76cjr54t8kx45jjw4j4k9j5hsr5m26&FailedURI=... @1:270)

**Comment by aurorasmiles** [comment]
Inital question answered, compiling errors probably due to internet issues
