### ISSUE TITLE
Spamming console when creating group

### ISSUE THREAD

**Issue by ItsNotAlan** [weaondara/BungeePerms#347]
**Describe the bug**
Spamming my console 

**To Reproduce**
Create a group 

**Expected behavior**
Spam my console

**Screenshots or log**
in file
[err.txt](https://github.com/weaondara/BungeePerms/files/3193371/err.txt)

**Additional context**
I am using MySQL provided by my host provider 
Travertine latest, Bungeeperms latest, protocol lib installed

**Comment by weaondara** [comment]
i don't think that u are using the latest of bungeeperms 
what's ur version?
latest is 3.0-dev-#70

**Comment by weaondara** [comment]
btw you are using the mysql backend which is deprecated for a long time now
you should migrate to the mysql2 backend
mysql backend no longer available

**Comment by aurorasmiles** [comment]
No answer, assuming it's fixed
