### ISSUE TITLE
PlotSquared Permission not working

### ISSUE THREAD

**Issue by OwnedGG** [weaondara/BungeePerms#348]
**Describe the bug**
PlotSquared permissions like plots.plot.4 to grant group permission to claim a defined amount of plots (in this case 4) is not working. PEX had no problem with that. Players can't claim any plots because i cant set max allowed claims for the group. If i grant the permission plots.plot.* it works, but then they have unlimited permission to claim plots

**To Reproduce**
Use Bungeeperms with PlotSquared and give user default permission fpr PlotSquared

**Expected behavior**
should be clear

**Screenshots or log**
-

**Additional context**
-

**Comment by aurorasmiles** [comment]
Hi, we are currently on vacation, but we will look at that ASAP :)

**Comment by OwnedGG** [comment]
glad to hear that. enjoy your vacation :)

**Comment by aurorasmiles** [comment]
Just to make the bughunt easier:
- Is the permission (plots.plot.4) correctly in the database after adding it via command?
If yes: What does _/bp group [Group] has plots.plot.4_ return?

Could you try turning on bp debug, and see what happens when you try to buy a plot with the permission?

**Comment by OwnedGG** [comment]
Hi there,

**bp group [Group] has plots.plot.4 returned: true**
bp recognized it but they still dont have permission to claim plots.
i never had that problem with my own plugins, but i remember i experienced a similar failure with mcmmo and griefprevention before. (Workaround if anybody reads this: give regex perms with "*" and take the perms u dont want away with -<perm>   -- dunno why that works makes no sense to me)

and i added 100% the correct perms its no coniguration fault. and i kinda just added the perms from pex to bp, so if it works on pex it should also work on bp i guess

turned bp debuging on, prints nothing into the log if i try to claim plot

**Comment by weaondara** [comment]
hi,
i just took a look at the ps code. 
is superpermscompat enabled on ur server?
which player did u test with?
whats the plot limit in ps?

**Comment by OwnedGG** [comment]
superpermscompat was disabled. im @ work atm. i will test later if it works now :)

**Comment by aurorasmiles** [comment]
Any updates on this issue @OwnedGG ?

**Comment by antwerpcraft** [comment]
so all the files from this plugin are still there but, all the plot areas and claims are just gone, please help me asap

**Comment by aurorasmiles** [comment]
How does this relate to this issue?
Please open your own issue and provide more information.

**Comment by aurorasmiles** [comment]
No answer, assuming it is fixed
