### ISSUE TITLE
Error with certain Essentials features

### ISSUE THREAD

**Issue by TrollyLoki** [weaondara/BungeePerms#349]
**Describe the bug**
Essentials throws an error caused by a bungeeperms method whenever someone puts a message in chat, and this seems to stop EssentialsChat from converting formatting and color codes

**To Reproduce**
Load Essentials, EssentialsChat, and BungeePerms, type a message in chat

**Expected behavior**
When I type a message in chat it should convert color codes as expected and not throw errors

**Screenshots or log**
https://pastebin.com/NFBCMLEY

**Additional context**
A similar error is thrown when certain Essentials commands are executed such as /nick
https://pastebin.com/xyfFR5wX

I have asked the EssentialsX team if it is a bug on their side and they said that it is a BungeePerms problem

**Comment by aurorasmiles** [comment]
Thanks for reporting this, we think we have already found the issue and are working on fixing it :)

**Comment by TrollyLoki** [comment]
Awesome! Thanks

**Comment by aurorasmiles** [comment]
Fixed in build 71
http://ci.wea-ondara.net/job/BungeePerms/71/artifact/target/BungeePerms-3.0-dev-71.jar
