### ISSUE TITLE
I can't give myself OP and perms!

### ISSUE THREAD

**Issue by Gabe2008** [weaondara/BungeePerms#364]
Hi, so I downloaded bp and put it in the plugins folder on all my serves, I went and did some editing in the config and it still doesnt let me do anything! When I give myself OP on the lobby server, it says im opped throught the console, but ingame it doesnt let me do anything. Please help me, thanks
![Screenshot_1](https://user-images.githubusercontent.com/48631193/72262212-662eb300-360e-11ea-8445-4d38428f8a01.png)

**Comment by aurorasmiles** [comment]
OP does not mean that you have any permission. You can give yourself permissions via the _/bp user USERNAME addperm PERM_ command.
Usually you create a group like owner with
/bp group Owner create
add yourself to the group
/bp user USERNAME addgroup Owner
and give the group owner the permissions you need.
You can do these commands via the console.

If you just want to have every permission, use /bp user USERNAME addperm *
this will give you every permission.
Please use the discord for further questions, GitHub is not for support.
