### ISSUE TITLE
Per Server Perms and Prefix's

### ISSUE THREAD

**Issue by DarthMarkain** [weaondara/BungeePerms#37]
Edit to add build number:

Build: BungeePerms 2.1

Hay there, first let me say thanks for the awesome work, and to all those people who keep asking you about a prefix/suffix plug-in, what they are looking for is CloudChat.

Now on to the issues.
Issue 1

I'm having trouble getting my setup to grant perms to specific servers, and having trouble with prefixes as well. Global stuff is all working fine (including the prefixes).

I'm using bungeeperms and bungeeperms bukkit (with its bridge) with a MySQL backend. Everything connects and is working for global groups.

However, when I try to configure per server perms or in fact per server anything, it just does not register, anywhere. Yes, I did set my server name in the config.yml on the bukkit end of things. Yes, it dose match the server name in Config.yml in bungee cord. 
Command being used in BungeeCord Terminal window:

bp group [Group-name] addperm [permission] [server]

bp group SNeonate addperm essentials.warps.* Skyblock

The result of this seems to be nothing, no new entry is added despite returning as a success. However when I do this:

bp group SNeonate addperm (essentials.warps.*) Skyblock

MySQL table looks like this for the entry:

id: 205
key: groups.SNeonate.servers.Skyblock.permissions
Value: (essentials.warps.*)

Now, knowing that having those brackets in there will mess everything up I then edit it to look like this:

id: 205
key: groups.SNeonate.servers.Skyblock.permissions
value: essentials.warps.*

So all I do is remove those brackets. Problem is that it still does not register the permissions the group SNeonate on server Skyblock. It should be noted, that if I give this node to SNeonate on global, it does work, on all servers, which of course neatly defeats what I'm aiming to do.

The prefixes also do not appear to work per server, I am imagining what the issues are linked. However I could be wrong. Just incase, SQL entry for the prefix is:

ID:184
Key: groups.SNeonate.servers.Skyblock.prefix
value: Neonate

It should be noted i have tested this with bungee only perms as well, and the issue is the same. 

Issue 2

When issuing a remove command of any kind, the bungeecord terminal throws up a lot of errors, that basically translate to bad SQL code. Naturally it does not remove the entry form the MySQL table. However it does say it did. 
This is not a major issue, as I can and have been going into the table and removing the entries manually. 
Thank you for taking the time to read this, and if you could point me to were I'm going wrong I would greatly appreciate it. 

Once again many Thanks - DarthMarkain

**Comment by tuxillator** [comment]
Perhaps close this and reopen a new feature for Server based prefixes?
