### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by ItzEfeYT** [weaondara/BungeePerms#372]
When I create the Founder group, giving it all the permissions ('*' and all the single perms) but when I give it to anyone he can't use the commands.

**Example:** I have a custom bungee cord staff chat, and the perm is "bungee.staff". When I set up the group with that perm, the guy that receives the group can't use the staff chat.

**Screenshots:** https://prnt.sc/sfhg85 | https://prnt.sc/sfhgdx | https://prnt.sc/sfhguo

**Comment by aurorasmiles** [comment]
This is most likely due to incorrect configuration. Please refer to the wiki for setup, if you need help you can join our Discord.
