### ISSUE TITLE
Can't run the plugin on a Waterfall server

### ISSUE THREAD

**Issue by Crystalflxme** [weaondara/BungeePerms#375]
I'm having trouble with running BungeePerms on a Waterfall server. I tested a few builds, even including old ones, to have the same issue. I'm assuming it's causing the plugin to not run correctly because no permissions for "bungeeperms" show up. I'm not currently able to use the plugin at all because I can't configure the permissions to allow me to utilize any commands.

Is it due to the plugin running on Waterfall?

**Reproducing the bug**
1. Start a Waterfall server
2. Put a build of BungeePerms in plugins
3. Run the Waterfall server
4. Check the debug.log to see the log errors

Note that this happens if you don't even touch the BungeePerms folder.

**Log**
Here is the entire debug.log after running the plugin:
```
23.06.2020 22:47:45: invalidate cache for group Builder
23.06.2020 22:47:45: invalidate cache for group Mod
23.06.2020 22:47:45: invalidate cache for group Admin
```

**Comment by aurorasmiles** [comment]
Hey there,
just starting BungeePerms on Waterfall works fine for me. Could you furhter elaborate what you mean?

**Comment by aurorasmiles** [comment]
Mh, okay. The "invalidate cache" debug message is just the plugin refreshing cached permissions, which is normal and good. As I can't replicate your issue at all, I've tried multiple times, I'm gonna close thise now. If you ever decide to use BP again and have issues, please open a new ticket, then we can figure out why stuff isn't working
