### ISSUE TITLE
Timed permissions, too short (24 days maximum)

### ISSUE THREAD

**Issue by tiradorus** [weaondara/BungeePerms#379]
Helo there! i use bungee perms and i have a little problem =)

I have some monthly grade on my server and ... we can't add a player for more than 24 days into a grade.

When you try to do for exemple : " /bp addtimedgroup <player> <group> 25d " then nothing happen.
However, if you do the same command but with 24 days long, it works.

So i ask you if you can up a little bit more the range of the timed-permissions duration, to at last 31 days ^^'

Thank you!

**Comment by weaondara** [comment]
you can find the fixed version at https://ci.wea-ondara.net/job/BungeePerms/ in a few minutes

**Comment by weaondara** [comment]
appeartly something went wrong on the build server, we're investigating

**Comment by aurorasmiles** [comment]
Fixed version is on the repo now :)
