### ISSUE TITLE
/bp overview is listing non-default groups as default

### ISSUE THREAD

**Issue by tycrek** [weaondara/BungeePerms#383]
**Describe the bug**
I have two groups: Admin and User. Admin is set to not be default while User is. When I run `/bp overview`, I see both listed as "Default". However when I run `/bp group <name> info`, Admin shows `false` for default and User shows `true` (as expected).

**To Reproduce**
Create two groups, one default and one non-default, then run `/bp overview`.

**Expected behavior**
Non-default groups should not show "Default" in overview command.

**Screenshots or log**
![image](https://user-images.githubusercontent.com/29926144/109689108-35774900-7b42-11eb-9370-9d5c1b8e9580.png)
![image](https://user-images.githubusercontent.com/29926144/109689162-41fba180-7b42-11eb-9611-33abc5b057da.png)
![image](https://user-images.githubusercontent.com/29926144/109689190-488a1900-7b42-11eb-924f-d9cf774b9240.png)

**Comment by aurorasmiles** [comment]
The `default` you see in overview is the ladder. Since the ladder of both ranks is called `default`, both ranks have that there in the overview. The default state isn't displayed in the overview at all

**Comment by tycrek** [comment]
Ahhh I see. Thank you for clarifying!
