### ISSUE TITLE
Error on Spigot server

### ISSUE THREAD

**Issue by lemnhut67** [weaondara/BungeePerms#385]
There was an error when BungeePerms b122 (latest version) is currently 3/4 time when the plugin is running on the Spigot server.

Specifically, when the player enters the server, the console will print an error:
https://pastebin.com/jXGFvYJn

**Comment by Cheos137** [comment]
Same issue here (using BungeePerms-4.0-dev-128 on a paper-1.16.5-636 server).
The stacktrace only appears on login, but no every time.

backend (type): YAML
useuuids: false

useregexperms: false
grouppermission: true
resolvingmode: SEQUENTIAL
allowops: true
superpermscompat: true

standalone: false

Other installed plugins:
BKCommonLib-1.16.5-v2, FastAsyncWorldEdit-Bukkit-1.16-668, LightCleaner-1.16.5-v1, LobBlock-1.16.5.1, Modern-LWC-2.1.5, OpenInv-4.1.6, PrefixSystem, PremiumVanish, ProtocolLib-4.6.0, worldguard-bukkit-7.0.4 + 2 custom plugins

**Comment by Cheos137** [comment]
To me it looks like the issue was introduced with 1b4f742, although i cannot exactly pinpoint the exception's cause

**Comment by aurorasmiles** [comment]
Probably fixed in 205a99620c04c6bd3bccc7876d487ed3be0aa21b
