### ISSUE TITLE
Disable message in lang.yml

### ISSUE THREAD

**Issue by Safarival** [weaondara/BungeePerms#386]
Hello,

Suggest 1:

Make it possible to deactivate a message.
Without the execution of the command, this sends an empty message in the chat.

Exemple:
debug:
  enabled: '&7Debug mode enabled.'
  
After disabling it:
debug:
  enabled: []
  
Suggest 2:

add permission for /bungeeperms command.
So that only the staff can see the information on the plugins for example

Thank you

**Comment by weaondara** [comment]
suggestion 1: fixed in 772663d
