### ISSUE TITLE
Add custom message

### ISSUE THREAD

**Issue by Safarival** [weaondara/BungeePerms#387]
Hello,

First message:

The message: "[BungeePerms] Command not found"
Cannot be changed in the file 'lang/en-GB.yml'

Example of when the message spawn:
/bp user <Pseudo> Test

Second message:

The message: "Too few arguments!" and "Too many arguments"
Cannot be changed in the file 'lang/en-GB.yml'

Example of when the message spawn:
/bp group <group>
/bp group <group> removetimedperm test.test 1h <serveur> <world>

Can you add this functionality please?

**Comment by weaondara** [comment]
fixed in 388a33d
