### ISSUE TITLE
Permission nodes with children

### ISSUE THREAD

**Issue by Sheepzez** [weaondara/BungeePerms#39]
Using BungeePerms + BungeePermsBukkit.

No Spigot/Bukkit plugins with parent/children type permission nodes work, I have to declare ALL children nodes, rather than just declare the parent. Take the example of this plugin: http://dev.bukkit.org/bukkit-plugins/chesscraft/pages/permissions/

Giving the node chesscraft.basic doesn't work (can't execute any of the commands), but giving all the nodes "chesscraft.commands.create.game", etc, works fine.

This is true for all plugins. If you could fix this problem, that would be amazing. I'd be able to remove so many nodes :).

Many thanks,
Sheepzez.

**Comment by tuxillator** [comment]
Isn't this fixed a long time ago with weaondara/BungeePermsBukkit@b09afde23dd08eceadcb157ec473f544120d4061 ?

**Comment by weaondara** [comment]
not fully
bungeeperms asks superperms if it couldn't find a rule but does check for child perms if there was a rule

**Comment by weaondara** [comment]
also see https://github.com/weaondara/BungeePermsBukkit/issues/6

**Comment by weaondara** [comment]
fixed in bp 3.0

**Comment by Sheepzez** [comment]
Almost exactly a year later! :+1:

**Comment by weaondara** [comment]
meh
