### ISSUE TITLE
Buycraft Shop (BungeePerms)

### ISSUE THREAD

**Issue by FabioWidmer** [weaondara/BungeePerms#47]
Hello

I can't make a Buycraft Shop with BungeePerms. I someone buy a package this person will not become the rank...

Please help me

Thanks

Fabio Widmer

**Comment by yolomaker** [comment]
weandara is there still no implementation of some sort of action

**Comment by weaondara** [comment]
sry no
and still no eta

**Comment by yolomaker** [comment]
Do you have a plugin channel where i can hook and maybe fork/make it and push it to you if it works love the bungee perms but now i'm starting a network and maybe we can make something working are we allowed to see if we can make it?

**Comment by xion87** [comment]
+ 1 please implement it or use bukkitplugins for do it

**Comment by weaondara** [comment]
in bp 3.0
