### ISSUE TITLE
Préfix / Suffix issue

### ISSUE THREAD

**Issue by SwatyB** [weaondara/BungeePerms#63]
I have installed your plugin next week but préfix and suffix still doesn't work.
It's normal ?
In the config file, admin have the préfix [A] but i doesn't work.

If you have Time to reply thanks you in advance.
Sorry for my bad english im French.

**Comment by tuxillator** [comment]
@SwatyB it's been over 6 months since activity on this issue, but for the sake of closure: I would not recommend Pex and BungeePerms both be installed. BungeePerms should be replacing the permissions and prefix resolution provided by Pex. Please close.

**Comment by weaondara** [comment]
see dev build at spigotmc

**Comment by weaondara** [comment]
works according to https://github.com/weaondara/BungeePermsBukkit/issues/5#issuecomment-75362511
