### ISSUE TITLE
Ignore UUID when useUUIDs is false?

### ISSUE THREAD

**Issue by TruDan** [weaondara/BungeePerms#70]
Is it possible to make it so when "useUUIDs" is false, it ignores UUID's completely. e.g. 
https://github.com/weaondara/BungeePerms/blob/master/src/main/java/net/alpenblock/bungeeperms/PermissionsManager.java#L625

`UUID uuid=e.getConnection().getUniqueId();`

So it wouldn't even do that ^

Reason being is i want to use this for a 1.6.4 bungeecord network, which of course errors when trying to use uuid's

**Comment by weaondara** [comment]
does 2.4 work?
