### ISSUE TITLE
How can I get the prefixes?

### ISSUE THREAD

**Issue by witterplay** [weaondara/BungeePerms#71]
I will write my own chat plugin for my lobby, but I don't know how to get the prefixes from bungeeperms. With vault it dont works :(

**Comment by phil568622** [comment]
Doesnt work with Vault for me too, bridge installed. PLS FIX!

**Comment by phil568622** [comment]
How to get the prefixes???? I tried 3 chat managers with and without vault, and i dont get it to work

**Comment by weaondara** [comment]
please tell me which chat managers so that i can test thx

**Comment by phil568622** [comment]
Essentials Chat & SimplePrefix. Both are Vault compatible...

weaondara <notifications@github.com> schrieb am Do., 19. Feb. 2015 23:28:

**Comment by phil568622** [comment]
Could you maybe answer to that:

https://github.com/weaondara/BungeePermsBukkit/issues/5
Im still trying to fix...

**Comment by weaondara** [comment]
ok i tested essentials chat just some hours ago ... i think i need to take another look at vault compat ...

**Comment by weaondara** [comment]
moved to weaondara/BungeePermsBukkit#5
please post further comments there
thx
