### ISSUE TITLE
Permission not working for me

### ISSUE THREAD

**Issue by EMGXF** [weaondara/BungeePerms#74]
@weaondara please help!
I have given permissions in the Bungee config.yml to my group. I have checked that I am part of the group, and that the group has the permissions, but when I run command, it says no permission.

**Comment by weaondara** [comment]
bungeecord config.yml or
bungeeperms config.yml

**Comment by EMGXF** [comment]
@weaondara Oh hey! Nice to see you are still active. I will give later, on my phone right now

**Comment by EMGXF** [comment]
http://pastebin.com/QsY137Xy BungeePerms Proxy config
http://pastebin.com/zEFGrqG4 BungeePerms Bukkit config

The databases for both are the same, I removed them for security

**Comment by EMGXF** [comment]
@weaondara

**Comment by weaondara** [comment]
your proxy backend and uuidplayerdb is yaml
use mysql2 for the backend and myql for uuidplayerdb for poxy and bukkit
and you shopud be fine

hint: you can use the migrate command for conversion

**Comment by EMGXF** [comment]
Oh right.
But then I will only be able to use commands for modifying permissions?
What I was looking for was a plugin where I can modify a file, and it will apply to all servers.

**Comment by weaondara** [comment]
when using mysql2 backend you can edit the db as well if you BUT you should be very careful to not corrupt it

reguarding to file option; you can create symlinks pointing to the permission.yml in your plugins folder of your proxy but i can't guarantee that it will work; additionally you may have to do a reload everytime you modified it via commands

the mysql solution was designed for multi-access, is well tested and works in production environment 

if you consider to use mysql please use to >>mysql2<< backend and >>mysql<< uuidplayerdb

**Comment by EMGXF** [comment]
Oh...the reason I chose this plugin was because I thought it was the solution to symlinks..
I will use PEX now.
Thanks weaondara for your time.
GL with the plugin

**Comment by weaondara** [comment]
thx
