### ISSUE TITLE
group.<groupname> automatic permissions

### ISSUE THREAD

**Issue by tuxillator** [weaondara/BungeePerms#76]
WorldGuard expects a permission of the format group.<groupname> when doing region membership/ownership checks, i.e. the builder group would have a permission group.builder. Without these they fail. They can be manually added, but it would be a far better user experience to have a config option that adds this automatically.

**Comment by weaondara** [comment]
is this a child perm problem like
group.builder:
   some.perm1
   some.perm2
?

**Comment by tuxillator** [comment]
Nope... it's literally a permissions node that is auto-generated for each group. Here's a concrete example - if you have a group called:
- visitor => contains `group.visitor` permission
- builder => contains `group.builder` permission
- mod => contains `group.mod` permission

This is used by WorldGuard to check group membership to regions, and probably some others. I manually add them today but other plugins (zPermissions in particular) have this functionality built in.

Probably should be implemented as a configuration option, i.e. `auto-group-permissions: true`.

p.s. probably should be flagged as feature request, don't think it's there while I'm browsing your source code...

**Comment by weaondara** [comment]
ok .. got it -> 2.7
