### ISSUE TITLE
Exceptions after reloading BungeePerms

### ISSUE THREAD

**Issue by recon88** [weaondara/BungeePerms#77]
Whenever I reload with /bungeeperms reload, it starts to throw exceptions. Relog doesn't help. Have to restart the server to fix it.... Using 2.4.0.  
http://pastebin.com/eg2NWbA1

**Comment by weaondara** [comment]
any previous errors?

**Comment by recon88** [comment]
No.  
It's 100% reproducible for me. So changing permissions and do a bungeeperms reload is impossible for me.  
Config file if that helps:  
```
debug:
  path: plugins/BungeePerms/debug.log
  showexceptions: false
  showlogs: false
bungeeperms:
  general:
    mysqlhost: localhost
    mysqlport: '3306'
    mysqldb: network
    mysqluser: mc
    mysqlpw: Rch9mBztD
backendtype: YML
tablePrefix: bperms_
uuidplayerdb: MySQL
useUUIDs: true
saveAllUsers: false
deleteUsersOnCleanup: false
uuidfetcher:
  cooldown: 3000
useregexperms: false
```

**Comment by weaondara** [comment]
seems that you're using yaml as permission backend
you probably should move to mysql2 backend

also note this:

backendtype: YML
-------------------^

an A is missing?

**Comment by recon88** [comment]
Tell me one good reason to switch over to mysql :)  

Also, adding the missing A fixed it. But why does it work until I reload? Defaulting to YAML on server start if nothing is set or set wrong? But throws an error if you reload? Kinda doesn't make sense to me. It should throw an error after server restart if you set something wrong there.

**Comment by weaondara** [comment]
yes it defaults to yaml
and it's rather complicated to change the error behavior
mysql reasons:
- no complicated symlinking of files (when using both parts of the plugin(bungee/bukkit) and yaml backend) if you do so
- easier editing of permissions (less errors in formatting)
- whatever reasons (for me: structured data should be in a db not in a special fomatted plain text file)

as this issue seems to be fixed -> close

**Comment by recon88** [comment]
Then it should default to yaml too when you reload the plugin :)  

Using BungeeCord Perms only, no Bukkit bridge.  
I find YAML way easier to edit because I would have to use SSH commands to change stuff inside my databases (no webserver, no phpmyadmin, no external connections allowed).

**Comment by weaondara** [comment]
ok when used bungeecord part only it doesn't matter (yaml is ok)

little tip: you can use port forwarding via ssh and use heidisql or something like that
