### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by xComputerguyx** [weaondara/BungeePerms#79]
I got BungeePerms and then edited all the permissions but then when I add myself to the group I don't get the prefix or any of the permissions please help! Here is my file. http://pastebin.com/mR8BgTd7

**Comment by xComputerguyx** [comment]
I fixed it... The only problem now is that the default group doesn't have any of their permissions working.

**Comment by xComputerguyx** [comment]
@weaondara Help  :+1:  Need this ASAP

**Comment by tuxillator** [comment]
The other groups work fine?

**Comment by xComputerguyx** [comment]
Yes all other groups work fine. Its just the default group.

**Comment by tuxillator** [comment]
Hmmm... this is working on my server. Try these in the BungeeCord console:

- Confirm the player is in the group you think they are in:
`bp user <username> info`
- See what effective permissions they have:
`bp user <username> list`

I would *expect* the first to show your user along with their membership in the default group. The second command would then show the list of permissions the default user has which should match the default group.

**Comment by xComputerguyx** [comment]
@tuxillator 

Ok so I figured out it works. Its just that 2 permission nodes are not working but they were working when I used Pex. Its a Kit plugin and faction. I made it so they have the default faction node when they do /f who they do not have any permissions. This was all working when I used pex. I dont know whats wrong with those 2 permissions. If you would like I can give you the IP address for the server and you can take a look for yourself.

**Comment by tuxillator** [comment]
what's the permission node you're using? It's probably a difference in the Pex resolver logic vs BungeePerms... I suspect it's related to wildcard permissions. Either way it seems BungeePerms is working?

**Comment by tuxillator** [comment]
Also I note your Factions permission node has an uppercase "F":
> `Factions.kit.fullplayer`

Perhaps should be `factions.kit.fullplayer`

**Comment by weaondara** [comment]
casing shpuldn't matter
are the faction permission for a bukkit plugin?
if so, do you use the mysql2 permission backend?

mysql2 as backend and mysql as uuidplayerdb should be used

**Comment by xComputerguyx** [comment]
I dont know which version of mySQL I use I just know I use mySQL

**Comment by weaondara** [comment]
'/bp migrate backend' should tell you
