### ISSUE TITLE
[FEATURE REQUEST] Some Improvements

### ISSUE THREAD

**Issue by phil568622** [weaondara/BungeePerms#80]
This is a very nice Plugin, but I have some Points you could add.

- Make BungeePermsBukkit and BungeePermsBukkitBridge one plugin - I dont know why they are seperated

- Add a config option to change the "No Permission" Text. (On Public Servers i would like to change it to the Unknown command message)

- Add the options to change prefix, suffix and displayname to users, not only groups.

- Fix some minor errors like a command not found message when doing "/bp group Group prefix" without a prefix specified.

Thanks,
Philip Ziegler

**Comment by tuxillator** [comment]
> Make BungeePermsBukkit and BungeePermsBukkitBridge one plugin - I dont know why they are separated

+1 vote for this feature. I'd be happy to do the pull request but I'm not sure @weaondara is accepting them.

On a related note you should probably file the first one against the BungeePermsBukkit repo instead, and the others as separate issues so they can be classified and prioritised.

**Comment by weaondara** [comment]
i'll take a loom at it

**Comment by weaondara** [comment]
*look

**Comment by weaondara** [comment]
created new issues for each


>Make BungeePermsBukkit and BungeePermsBukkitBridge one plugin - I dont know why they are >seperated

https://github.com/weaondara/BungeePerms/issues/89

>Add a config option to change the "No Permission" Text. (On Public Servers i would like to change it >to the Unknown command message)

https://github.com/weaondara/BungeePerms/issues/90

>Add the options to change prefix, suffix and displayname to users, not only groups.

https://github.com/weaondara/BungeePerms/issues/91

>Fix some minor errors like a command not found message when doing "/bp group Group prefix" >without a prefix specified.

https://github.com/weaondara/BungeePerms/issues/92

**Comment by phil568622** [comment]
Were split into multiple issues, so

//close
