### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tuxillator** [weaondara/BungeePerms#81]
@weaondara is this still (and the related Spigot and bridge projects) being actively maintained? I'd like to contribute but don't see much activity.

If you don't intend to maintain it, please advise under what license the code is under so a suitable fork can begin.

**Comment by weaondara** [comment]
i try to keep up as best as i can   and i intend to maintain it 
reguarding the license ... i'll think 'bout that

**Comment by tuxillator** [comment]
Thanks - this is an excellent set of plugins, I would hate to see it go the way many post-Bukkit plugins went.

As I said I'd be happy to help by providing PRs so long as they are reviewed/accepted (or declined with reason) and the licensing is suitable for contribution.

Can I also recommend aligning with a coding style standard? Eclipse supports both [Google](https://google-styleguide.googlecode.com/svn-history/r130/trunk/javaguide.html) and Sun standards out of the box.

I'll relabel this ticket and keep it open until you decide on licensing and contributors.

**Comment by weaondara** [comment]
>Can I also recommend aligning with a coding style standard? Eclipse supports both Google and Sun >standards out of the box.
first of all i use netbeans (this is just a personal opinion: eclipse is bullshit (bad layout, no bundled maven & git, a lot of crashes, gui fail design, ...))
reguarding code standard: it confuses me if i have to search for the beginning { bracket if it's not exactly at the same indention as the ending } bracket; this is the only exception from the general java cs i know

**Comment by tuxillator** [comment]
> it confuses me if i have to search for the beginning {

I feel the same way about doing it the other way :) Fortunately Eclipse can be configured, so I'll set opening brace to sit on a new line. For my reference: Preferences->Java->Code Style->Formatter Click on edit, and on the new opened window, go to the Braces tab.

> first of all i use netbeans

I started writing in Java again only recently so my opinions are not firm, but modern Eclipse isn't so bad... I've been using it in both Windows and OS X for perhaps 200 hours without crashes.

> no bundled maven & git

From the Eclipse IDE for Java Developers download, the above is included out of the box:

> The essential tools for any Java developer, including a Java IDE, a CVS client, Git client, XML Editor, Mylyn, Maven integration...

The main Eclipse irritation for me is the crap it puts in your project folder, but that can be ignored by git. Other IDEs (including Netbeans) like to put crap in your project folders but Eclipse is certainly one of the noisiest.

> bad layout

This one I don't really have thoughts on... I'll have to try Netbeans (and perhaps IntelliJ) for comparison.

I guess my 2 cents is it shouldn't matter what IDE the contributor is using, so long as the code is consistent and quality. Any thoughts on licensing and contribution in general? Seems you are pushing out a lot of code at the moment so I'm happy to file issues for now.

**Comment by weaondara** [comment]
ide decitions are - of course - idividual ... i prefer netbeans
i used eclipse a long time ago so thing s might have changed since then but i'm happy with netbeans and would never give it back
about licencing ... well i hate this topic as i have no idea of licensing except that that everything with has no license may not be redistributed ... it'll need some reading ... and some time

**Comment by tuxillator** [comment]
http://choosealicense.com - this helps slow my brain meltdown thinking about this stuff :)

**Comment by weaondara** [comment]
hm ...

**Comment by Janmm14** [comment]
@weaondara please

**Comment by weaondara** [comment]
now under mit license
