### ISSUE TITLE
write some doku

### ISSUE THREAD

**Issue by weaondara** [weaondara/BungeePerms#82]
meh.

**Comment by willowen100** [comment]
Server based permissions are not working. In the screenshot below I add a permission and then check it to see if it is there and it comes back as false.

https://flic.kr/p/qtjUZf://flic.kr/p/qtjUZf

**Comment by weaondara** [comment]
you're link is invalid
PLEASE CREATE A NEW ISSUE THX

**Comment by weaondara** [comment]
done ... a long time ago
