### ISSUE TITLE
Feature request: formalise Vault support

### ISSUE THREAD

**Issue by tuxillator** [weaondara/BungeePerms#86]
Vault "works" in that it's currently injected via reflection. Per the Vault team, we can add formal support by just sending them a pull request:

> If you have your own plugin that you believe should be supported, fork Vault or create a patch with the necessary changes. Additionally you can create an issue on Github and we'll get to it at our convenience.

[This is how other permissions plugins are implemented](https://github.com/MilkBowl/Vault/tree/master/src/net/milkbowl/vault/permission/plugins)

As part of completing this feature, should also make sure we call against [Vault API](https://github.com/MilkBowl/VaultAPI) instead of Vault directly.

**Comment by weaondara** [comment]
i already made a pull request for it but they rejected with the reason that vault adapter should be fully implemented (including the permissions modifications and so on) which is currently not possible

**Comment by phil568622** [comment]
Why isnt it possible?

**Comment by weaondara** [comment]
because bpb doesn't support perm editing atm
https://github.com/MilkBowl/Vault/pull/476

**Comment by tuxillator** [comment]
The methods that modify permissions (e.g. add/remove permissions, groups, prefixes, etc) were unimplemented in the original PR. See this:

https://github.com/weaondara/BungeePermsBukkit/blob/master/src/main/java/net/alpenblock/bungeeperms/bukkit/bridge/bridges/vault/Permission_BungeePermsBukkit.java

Once those "return false" methods contain an implementation I expect the Vault team would accept the new PR.

**Comment by weaondara** [comment]
as i said in #99 i'll make one plugin ... then there would be definitely no problem with that ... looking forward to it but i don't know how long it takes as studying at university is a hard, time intense job

**Comment by weaondara** [comment]
denied by vault https://github.com/MilkBowl/Vault/pull/779
don't really understand why
works anyway
