### ISSUE TITLE
Commands not available from Bukkit/Spigot server console

### ISSUE THREAD

**Issue by weaondara** [weaondara/BungeePerms#88]
from https://github.com/weaondara/BungeePermsBukkit/issues/3
by @tuxillator

**Comment by xion87** [comment]
+1  for this, usefull for donation plugins

**Comment by odium4u** [comment]
+1 for this - willing to put cash down to raise priority.

**Comment by phil568622** [comment]
Until we've got this implemented you could use this (http://www.spigotmc.org/resources/commandsync.115/) set it up, and then use like "/commandsync console bungee bp user Test add *"

This would only be a temporary solution, weaondara is working on BP3.0 and on making BungeePermsBukkit and BungeePerms one plugin that can be installed on bungees and spigot/bukkit servers...

**Comment by odium4u** [comment]
Thank you for the resource link. I will be sure to check it out.

**Comment by weaondara** [comment]
done ... available soon

**Comment by Digot** [comment]
How soon?

**Comment by xion87** [comment]
@Digot is already included in 3.0 version :)
