### ISSUE TITLE
combine bukkit and bridge

### ISSUE THREAD

**Issue by weaondara** [weaondara/BungeePerms#89]

**Comment by weaondara** [comment]
done in https://github.com/weaondara/BungeePermsBukkit/commit/cdc6d6f3883d4f4ec0eb265e64649eeb57cab1f6

**Comment by tuxillator** [comment]
Please re-open, 2 "cleanup" things:
- need to either remove or put a big fat warning up on the bridge repo that it's no longer in use
- on enable for bukkit plugin it would be a good idea to detect the old bridge plugin and throw a warning if it's installed to avoid unintended side-effects.

**Comment by weaondara** [comment]
1st: done already
2nd: wait a sec

**Comment by weaondara** [comment]
done via https://github.com/weaondara/BungeePermsBukkit/commit/3a66f1778b012b2e1054e3e464440d48198bdb18
