### ISSUE TITLE
Github Wiki Setup Tuturial

### ISSUE THREAD

**Issue by phil568622** [weaondara/BungeePerms#94]
Hey weaondara,

it looks like most oft the users fail to set up BungeePerms correctly, so it would be nice to create a Wiki on Github which is linked in the Spigot Post. I would like to write a Step-By-Step Setup Tuturial, but I wanted to ask you first ;)

Thanks, and sorry for my English,
Philip Ziegler

PS: Im from Germany

**Comment by weaondara** [comment]
permission granted
i appreciate any help 

PS: from austria

**Comment by phil568622** [comment]
Okay, thanks

//close
