### ISSUE TITLE
SQL sanitisation of input

### ISSUE THREAD

**Issue by tuxillator** [weaondara/BungeePerms#95]
Need to add SQL sanitising to anything passed through to the adapters. For example:
```
bp group mod prefix '
```
This will generate an MySQLSyntaxErrorException. I haven't tried it, but it may be possible to do something more nefarious via SQL injection:
```
bp group mod prefix `,null,null);drop\ table\ `bungeeperms_permissions2`;
```
Either way need to sanitise ANYTHING going to MySQL just in case.

**Comment by weaondara** [comment]
fixed in https://github.com/weaondara/BungeePerms/commit/42710c9e83da8b317da5d76cb7fb06cdb53c55a1
close
