### ISSUE TITLE
Not saving users in groups

### ISSUE THREAD

**Issue by cindyker** [weaondara/BungeePerms#96]
I'm using it bungee only with SQL
There is nothing in the debug.log.

We add users to groups like
/bungeeperms user fvqu setgroup Admin

it works until they log out, then it forgets their permissions.

This is my config:
debug:
  path: plugins/BungeePerms/debug.log
  showexceptions: true
  showlogs: false
bungeeperms:
  general:
    mysqlhost: localhost
    mysqlport: '3306'
    mysqldb: BungeePerms
    mysqluser: bungeecord
    mysqlpw: mypass
backendtype: MySQL
tablePrefix: bungeeperms_
uuidplayerdb: MySQL
useUUIDs: true
saveAllUsers: false
deleteUsersOnCleanup: false
uuidfetcher:
  cooldown: 3000
tabcomplete: false
useregexperms: false

**Comment by weaondara** [comment]
which users are not saved?

**Comment by weaondara** [comment]
according to you config only non default users are saved (only default groups; no extra permissions)
`saveAllUsers: false`

**Comment by cindyker** [comment]
I don't want every user saved.
I want my admins and moderators saved
Do I need to remove them from the default group?

**Comment by weaondara** [comment]
no as soon as the are not a default user they should be saved

**Comment by weaondara** [comment]
there no entries about the user in the permissions db?

**Comment by cindyker** [comment]
If I do:
/bungeeperms group Admin users
I get in came : No players found!

in the database I have a rows like this:
| 260 | users.d03e8446-cc92-4aab-a869-be2dfc036c64.groups | Admin    
| 259 | users.323c85fb-810a-4503-80c1-1ffcd7671fa4.groups | Admin   

However when they log in, they don't have permissions and we have to add it.

They also have default added as a group in the table. I can remove that if that is the issue.

**Comment by phil568622** [comment]
Maybe set the Backend to mysql2

**Comment by weaondara** [comment]
that exactly waht i wanted to suggest

**Comment by cindyker** [comment]
mysql2 ?
is that different than mysql?

**Comment by weaondara** [comment]
i'll deprecate the mysql backend in 2.6

**Comment by weaondara** [comment]
no just a much better layout and performance

**Comment by cindyker** [comment]
Will I need to do anything other than change it?

**Comment by weaondara** [comment]
you can migrate it ... or just change the backends in all configs

**Comment by phil568622** [comment]
Just do /bp backend mysql3

**Comment by cindyker** [comment]
mysql3 or mysql2?

**Comment by weaondara** [comment]
better /bp migrate backend mysql2

**Comment by phil568622** [comment]
*mysql2

**Comment by cindyker** [comment]
ok, I did that
I am still getting No players found for /bp group Mod users
but when I try to add 
/bp user Guerra072 addgroup Mod
it tells me he's already in the group .

**Comment by weaondara** [comment]
are they in db?

**Comment by cindyker** [comment]
they are in bungeeperms_permissions but not in bungeeperms_permissions2

**Comment by weaondara** [comment]
permissions2 matters .. forget the normal table

**Comment by weaondara** [comment]
so you have to add them again ...

**Comment by cindyker** [comment]
but it kept his permissions.
so its in memory just not saving to the database.
I removed his group and readded it , and it added it to permission2 
and it added both default and Mod

**Comment by cindyker** [comment]
Ok it looks to be working now. :+1: 
Thank you!

**Comment by weaondara** [comment]
maybe a /bp reload would help

**Comment by phil568622** [comment]
Just delete bungeeperms_permissions table

**Comment by phil568622** [comment]
weaondara, Im already writing a setup tuturial, that would prevent issues like not using mysql2...

**Comment by weaondara** [comment]
mysql backend will be deprecated in 2.6

**Comment by weaondara** [comment]
just an info: https://github.com/weaondara/BungeePerms/commit/a668d731744cff11e4faec951fe39c90f19820ae and #97
