### ISSUE TITLE
Releases on Github

### ISSUE THREAD

**Issue by tuxillator** [weaondara/BungeePerms#99]
@weaondara can you also put the releases here on Github using the [releases](https://github.com/weaondara/BungeePerms/releases) feature? May as well put both the BungeeCord and Bukkit plugins under BungeePerms repo for simplicity. Can then add readme.md to reference releases, documentation etc.

I love being a pain, but the project is improving rapidly and can feel it gaining momentum :)

**Comment by weaondara** [comment]
i aiming to combine both plugins like i'm doing it with bukkit part and bridge
i didn't know about the releases feature .. i'll need some information beforehand to use it ... i'll read the doku 'bout that

**Comment by tuxillator** [comment]
By "combine", do you mean combine the repositories and have maven modules generate the separate artefacts?

**Comment by phil568622** [comment]
I think he means sth. like FreeBungeeChat did. They have one .jar that can has the bungee parts and the bukkit plugin inside, and can be installed on bukkit and bungee servers

**Comment by weaondara** [comment]
yeah, there only one jar and can be put on both bungee and spigot
